In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('HR RAW DATA.csv')
df.head()

Unnamed: 0 Age Attrition BusinessTravel DailyRate  \
0           0  51        No            NaN    684,0$   
1           1  52        No            NaN    699,0$   
2           2  42        No  travel_rarely    532,0$   
3           3  47        No  travel_rarely    359,0$   
4           4  46        No            NaN   1319,0$   

                 Department  DistanceFromHome  Education    EducationField  \
0                       NaN                 6          3               NaN   
1                       NaN                 1          4     Life Sciences   
2   Research & Development                  4          2  Technical Degree   
3                       NaN                 2          4           Medical   
4                       NaN                 3          3  Technical Degree   

   employeecount  ... YearsAtCompany  YearsInCurrentRole  \
0              1  ...             20                 NaN   
1              1  ...             33                 NaN   
2              1  ...             22                 NaN   
3              1  ...             20                 NaN   
4              1  ...             19                 NaN   

   YearsSinceLastPromotion YEARSWITHCURRMANAGER  SameAsMonthlyIncome  \
0                       15                   15              19537,0   
1                       11                    9              19999,0   
2                       11                   15              19232,0   
3                        5                    6              17169,0   
4                        2                    8                  NaN   

   DateBirth       Salary                       RoleDepartament  \
0       1972  1000000000$                                   NaN   
1       1971  1000000000$                                   NaN   
2       1981  1000000000$   ManaGER  -  Research & Development    
3       1976  1000000000$                                   NaN   
4       1977  1000000000$                                   NaN   

  NUMBERCHILDREN RemoteWork  
0            NaN        Yes  
1            NaN          1  
2            NaN          1  
3            NaN      False  
4            NaN          0  

[5 rows x 42 columns]

`Nombre de las columnas`

In [5]:
df.columns

Index(['Unnamed: 0', 'Age', 'Attrition', 'BusinessTravel', 'DailyRate',
       'Department', 'DistanceFromHome', 'Education', 'EducationField',
       'employeecount', 'employeenumber', 'EnvironmentSatisfaction', 'Gender',
       'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole',
       'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'MonthlyRate',
       'NUMCOMPANIESWORKED', 'Over18', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours',
       'StockOptionLevel', 'TOTALWORKINGYEARS', 'TrainingTimesLastYear',
       'WORKLIFEBALANCE', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YEARSWITHCURRMANAGER',
       'SameAsMonthlyIncome', 'DateBirth', 'Salary', 'RoleDepartament',
       'NUMBERCHILDREN', 'RemoteWork'],
      dtype='object')

In [6]:
# Variables categoricas con las númericas
df.describe(include= 'all').T

count unique                       top  freq  \
Unnamed: 0                1614.0    NaN                       NaN   NaN   
Age                         1614     54                        35    84   
Attrition                   1614      2                        No  1355   
BusinessTravel               842      3             travel_rarely   586   
DailyRate                   1614    849                      nan$   124   
Department                   302      3   Research & Development    196   
DistanceFromHome          1614.0    NaN                       NaN   NaN   
Education                 1614.0    NaN                       NaN   NaN   
EducationField               869      6             Life Sciences   349   
employeecount             1614.0    NaN                       NaN   NaN   
employeenumber              1183   1079                     482,0     2   
EnvironmentSatisfaction   1614.0    NaN                       NaN   NaN   
Gender                    1614.0    NaN                       NaN   NaN   
HourlyRate                  1614     72             Not Available    84   
JobInvolvement            1614.0    NaN                       NaN   NaN   
JobLevel                  1614.0    NaN                       NaN   NaN   
JobRole                     1614   1579                  mANager      4   
JobSatisfaction           1614.0    NaN                       NaN   NaN   
MaritalStatus                963      5                   Married   404   
MonthlyIncome                771    668                    6347,0     4   
MonthlyRate               1614.0    NaN                       NaN   NaN   
NUMCOMPANIESWORKED        1614.0    NaN                       NaN   NaN   
Over18                       713      1                         Y   713   
OverTime                     938      2                        No   682   
PercentSalaryHike         1614.0    NaN                       NaN   NaN   
PerformanceRating           1419      2                       3,0  1205   
RelationshipSatisfaction  1614.0    NaN                       NaN   NaN   
StandardHours                419      1                      80,0   419   
StockOptionLevel          1614.0    NaN                       NaN   NaN   
TOTALWORKINGYEARS           1088     40                      10,0   144   
TrainingTimesLastYear     1614.0    NaN                       NaN   NaN   
WORKLIFEBALANCE             1506      4                       3,0   913   
YearsAtCompany            1614.0    NaN                       NaN   NaN   
YearsInCurrentRole            34     10                       2,0    11   
YearsSinceLastPromotion   1614.0    NaN                       NaN   NaN   
YEARSWITHCURRMANAGER      1614.0    NaN                       NaN   NaN   
SameAsMonthlyIncome          771    668                    6347,0     4   
DateBirth                 1614.0    NaN                       NaN   NaN   
Salary                      1614      1               1000000000$  1614   
RoleDepartament              302    301        MaNAgeR  -  Sales      2   
NUMBERCHILDREN               0.0    NaN                       NaN   NaN   
RemoteWork                  1614      5                         1   360   

                                  mean          std     min     25%      50%  \
Unnamed: 0                       806.5   466.065982     0.0  403.25    806.5   
Age                                NaN          NaN     NaN     NaN      NaN   
Attrition                          NaN          NaN     NaN     NaN      NaN   
BusinessTravel                     NaN          NaN     NaN     NaN      NaN   
DailyRate                          NaN          NaN     NaN     NaN      NaN   
Department                         NaN          NaN     NaN     NaN      NaN   
DistanceFromHome              4.527261    14.591913   -49.0     2.0      5.0   
Education                     2.925031     1.022357     1.0     2.0      3.0   
EducationField                     NaN          NaN     NaN     NaN      NaN   
e

In [7]:
 
'Age' # Revisar los años que estan en letras, porque son de números 
'Attrition' # OK
'BusinessTravel' # revisar los NAN
'DailyRate' # OK
'Department' # revisar los NAN
'DistanceFromHome' # Revisar porque son (-)negativos y otros (+)positivos 
'Education' # OK
'EducationField' # Revisar los NAN
'employeecount' # Ok 

'EnvironmentSatisfaction' # Ok 
'Gender' # Cambiar los valores, estan en 0 y 1 y hay que ponerlos M - F
'HourlyRate' # OK
'JobInvolvement' # OK
'JobLevel' # OK
'JobRole' # Cambiar palabras con minusculas y mayusculas 
'JobSatisfaction' # OK
'MaritalStatus' # revisar los NAN
'MonthlyIncome' # revisar los NAN
'MonthlyRate' # OK

'NUMCOMPANIESWORKED' # OK
'Over18' # revisar los NAN
'OverTime' # revisar los NAN
'PercentSalaryHike' # OK
'PerformanceRating' # revisar los NAN
'RelationshipSatisfaction' # OK
'StandardHours' # revisar los NAN
'StockOptionLevel' # OK
'TOTALWORKINGYEARS' # revisar los NAN
'TrainingTimesLastYear' # OK

'WORKLIFEBALANCE' # revisar los NAN
'YearsAtCompany' # OK
'YearsInCurrentRole' # revisar los NAN
'YearsSinceLastPromotion' # OK
'YEARSWITHCURRMANAGER' # OK
'SameAsMonthlyIncome' # revisar los NAN
'DateBirth' # OK
'Salary' # OK
'RoleDepartament' # revisar los NAN, y las mayus y minusculas tambien porque losnombre se repiten 
'NUMBERCHILDREN' # revisar los NAN
'RemoteWork' #  Revisa los False y los Trues porque solo hay SI

'RemoteWork'

In [8]:
age_dict = list(df['Age'].unique())  # algunos no son números sino letras, hay que cambiarlos
print(age_dict)
print(df['Age'].dtype)

['51', '52', '42', '47', '46', '48', '59', '41', '56', '38', '55', '40', '58', '35', '45', '33', '36', '34', 'forty-seven', '53', '43', '60', '32', '37', '49', '39', '50', '44', '30', 'fifty-eight', '29', '31', '54', '57', '27', 'thirty-six', '28', '26', 'fifty-five', '25', 'fifty-two', 'thirty-one', '24', 'thirty', '23', '22', '21', '20', 'twenty-six', '19', 'thirty-seven', '18', 'thirty-two', 'twenty-four']
object


In [67]:
income1_dict = list(df['MonthlyIncome'].unique())  # algunos no son números sino letras, hay que cambiarlos
print(income1_dict)
print(df['Age'].dtype)

['19537,0', '19999,0', '19232,0', '17169,0', nan, '17174,0', '16595,0', '19973,0', '13402,0', '13206,0', '19545,0', '18041,0', '19246,0', '10748,0', '16752,0', '6201,0', '19845,0', '4001,0', '10447,0', '16064,0', '3210,0', '10266,0', '10475,0', '6162,0', '4721,0', '4615,0', '16959,0', '10306,0', '5406,0', '5902,0', '10855,0', '5914,0', '6646,0', '13973,0', '13320,0', '6687,0', '4735,0', '13872,0', '19045,0', '16015,0', '9613,0', '11510,0', '4306,0', '17046,0', '5067,0', '3692,0', '19847,0', '2308,0', '5747,0', '10422,0', '6347,0', '2348,0', '3072,0', '12490,0', '8020,0', '17068,0', '8943,0', '19272,0', '5577,0', '2691,0', '7403,0', '8823,0', '3579,0', '17779,0', '18213,0', '13577,0', '19190,0', '17123,0', '19187,0', '10008,0', '7988,0', '7083,0', '4723,0', '3407,0', '2929,0', '12031,0', '15427,0', '5126,0', '9619,0', '5010,0', '19033,0', '10400,0', '2793,0', '5674,0', '19197,0', '8412,0', '3348,0', '5309,0', '7654,0', '12808,0', '6586,0', '2519,0', '17099,0', '13120,0', '3131,0', '4444

In [68]:
income1_null=df.isnull().sum()

In [69]:
income1_null

Unnamed: 0                     0
Age                            0
Attrition                      0
BusinessTravel               772
DailyRate                      0
Department                  1312
DistanceFromHome               0
Education                      0
EducationField               745
employeecount                  0
employeenumber               431
EnvironmentSatisfaction        0
Gender                         0
HourlyRate                     0
JobInvolvement                 0
JobLevel                       0
JobRole                        0
JobSatisfaction                0
MaritalStatus                651
MonthlyIncome                843
MonthlyRate                    0
NUMCOMPANIESWORKED             0
Over18                       901
OverTime                     676
PercentSalaryHike              0
PerformanceRating            195
RelationshipSatisfaction       0
StandardHours               1195
StockOptionLevel               0
TOTALWORKINGYEARS            526
TrainingTi

# Posible code para cambiar los str a int, esta solo los identifica

In [9]:
# Obtener los valores únicos de la columna 'Age'
age_dict = list(df['Age'].unique())

# Función para convertir cadenas a números
def convert_to_number(age):
    try:
        return int(age)
    except ValueError:
        return f"Error converting '{age}'"

# Aplicar la función de conversión a la lista de edades únicas
converted_ages = [convert_to_number(age) for age in age_dict]

# Separar las edades convertidas y los errores
converted_ages_only1 = [age for age in converted_ages if isinstance(age, int)]
errors = [age for age in converted_ages if isinstance(age, str)]

# Mostrar los resultados
print("Converted Ages:")
print(converted_ages_only1)

print("\nErrors:")
print(errors)


Converted Ages:
[51, 52, 42, 47, 46, 48, 59, 41, 56, 38, 55, 40, 58, 35, 45, 33, 36, 34, 53, 43, 60, 32, 37, 49, 39, 50, 44, 30, 29, 31, 54, 57, 27, 28, 26, 25, 24, 23, 22, 21, 20, 19, 18]

Errors:
["Error converting 'forty-seven'", "Error converting 'fifty-eight'", "Error converting 'thirty-six'", "Error converting 'fifty-five'", "Error converting 'fifty-two'", "Error converting 'thirty-one'", "Error converting 'thirty'", "Error converting 'twenty-six'", "Error converting 'thirty-seven'", "Error converting 'thirty-two'", "Error converting 'twenty-four'"]


In [10]:
len(converted_ages_only1)

43

# Esta opción nos lo devuelve convertido en int todos los datos qe antes erán str

In [11]:
import pandas as pd

# Supongamos que tienes un DataFrame con una columna 'Age'
data = {'Age': ['51', '52', '42', '47', '46', '48', '59', '41', '56', '38', '55', '40', '58', '35', '45', '33', '36', '34', 'forty-seven', '53', '43', '60', '32', '37', '49', '39', '50', '44', '30', 'fifty-eight', '29', '31', '54', '57', '27', 'thirty-six', '28', '26', 'fifty-five', '25', 'fifty-two', 'thirty-one', '24', 'thirty', '23', '22', '21', '20', 'twenty-six', '19', 'thirty-seven', '18', 'thirty-two', 'twenty-four']}
df_2 = pd.DataFrame(data)

# Obtener los valores únicos de la columna 'Age'
age_dict = list(df['Age'].unique())

# Diccionario para convertir palabras a números
word_to_number = {
    'zero': 0, 'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five': 5,
    'six': 6, 'seven': 7, 'eight': 8, 'nine': 9, 'ten': 10, 'eleven': 11,
    'twelve': 12, 'thirteen': 13, 'fourteen': 14, 'fifteen': 15,
    'sixteen': 16, 'seventeen': 17, 'eighteen': 18, 'nineteen': 19,
    'twenty': 20, 'thirty': 30, 'forty': 40, 'fifty': 50, 'sixty': 60,
    'seventy': 70, 'eighty': 80, 'ninety': 90
}

# Función para convertir cadenas a números
def convert_to_number(age):
    try:
        # Primero intentamos convertir directamente a entero
        return int(age)
    except ValueError:
        # Si falla, intentamos convertir usando el diccionario
        words = age.split('-')
        number = 0
        for word in words:
            if word in word_to_number:
                number += word_to_number[word]
            else:
                return f"Error converting '{age}'"
        return number

# Aplicar la función de conversión a la lista de edades únicas
converted_ages = [convert_to_number(age) for age in age_dict]

# Separar las edades convertidas y los errores
converted_ages_only = [age for age in converted_ages if isinstance(age, int)]
errors = [age for age in converted_ages if isinstance(age, str)]

# Mostrar los resultados
print("Converted Ages:")
print(converted_ages_only)
print("\nErrors:")
print(errors)


Converted Ages:
[51, 52, 42, 47, 46, 48, 59, 41, 56, 38, 55, 40, 58, 35, 45, 33, 36, 34, 47, 53, 43, 60, 32, 37, 49, 39, 50, 44, 30, 58, 29, 31, 54, 57, 27, 36, 28, 26, 55, 25, 52, 31, 24, 30, 23, 22, 21, 20, 26, 19, 37, 18, 32, 24]

Errors:
[]


In [12]:
len(converted_ages_only)

54

In [13]:
attri_dict= list(df['Attrition'].unique())
print(attri_dict)

['No', 'Yes']


In [14]:
busi_dict= list(df['BusinessTravel'].unique()) # revisar los NAN
print(busi_dict)

[nan, 'travel_rarely', 'travel_frequently', 'non-travel']


In [15]:
daily_dict= list(df['DailyRate'].unique()) 
print(daily_dict)

['684,0$', '699,0$', '532,0$', '359,0$', '1319,0$', '117,0$', '1435,0$', '635,0$', '1276,0$', '840,0$', '247,0$', '1369,0$', '201,0$', '1360,0$', '692,0$', '1398,0$', '286,0$', '1402,0$', '819,0$', '884,0$', '1238,0$', '515,0$', '1223,0$', '202,0$', '928,0$', '607,0$', '266,0$', '429,0$', '589,0$', 'nan$', '1180,0$', '1282,0$', '776,0$', '665,0$', '526,0$', '1034,0$', '1403,0$', '1499,0$', '580,0$', '859,0$', '263,0$', '1376,0$', '885,0$', '1003,0$', '1321,0$', '394,0$', '1372,0$', '1333,0$', '228,0$', '737,0$', '823,0$', '667,0$', '301,0$', '573,0$', '1329,0$', '630,0$', '1063,0$', '1017,0$', '1296,0$', '939,0$', '1355,0$', '1448,0$', '200,0$', '1202,0$', '404,0$', '208,0$', '813,0$', '465,0$', '1189,0$', '1001,0$', '1394,0$', '161,0$', '288,0$', '682,0$', '1354,0$', '147,0$', '119,0$', '1413,0$', '452,0$', '334,0$', '1132,0$', '982,0$', '480,0$', '1099,0$', '672,0$', '1379,0$', '583,0$', '1492,0$', '1050,0$', '469,0$', '237,0$', '1440,0$', '1291,0$', '1157,0$', '1336,0$', '1224,0$', 

In [16]:
depart_dict= list(df['Department'].unique()) # revisar los NAN
print(depart_dict)

[nan, ' Research & Development ', ' Sales ', ' Human Resources ']


In [17]:
distance_dict= list(df['DistanceFromHome'].unique()) # Revisar porque son (-)negativos y otros (+)positivos 
print(distance_dict)

[6, 1, 4, 2, 3, 22, 25, 9, 7, 23, 10, 12, 14, -13, 15, 8, -42, 28, -37, 5, 16, -35, 26, -26, 24, 29, -25, 17, 21, -18, -10, -30, -27, 20, -31, -29, -39, 18, -21, -15, 11, 13, -14, 19, -33, -34, -46, -36, -19, 27, -12, -23, -45, -28, -47, -32, -24, -16, -22, -41, -49, -11, -48, -38, -20, -17, -43, -40, -44]


In [18]:
edu_dict= list(df['Education'].unique())
print(edu_dict)

[3, 4, 2, 1, 5]


In [19]:
edu_f_dict= list(df['EducationField'].unique()) # Revisar los NAN
print(edu_f_dict)

[nan, 'Life Sciences', 'Technical Degree', 'Medical', 'Other', 'Marketing', 'Human Resources']


In [20]:
employ_dict= list(df['employeecount'].unique())
print(employ_dict)

[1]


In [21]:
employ_num_dict= list(df['employeenumber'].unique())
print(employ_num_dict)

['162,0', '259,0', '319,0', nan, '1900,0', '81,0', '387,0', '999,0', '1035,0', '58,0', '558,0', '825,0', '1712,0', '73,0', '820,0', '1294,0', '1774,0', '1815,0', '1993,0', '32,0', '100,0', '244,0', '327,0', '373,0', '729,0', '830,0', '981,0', '1042,0', '1080,0', '1995,0', '145,0', '158,0', '391,0', '436,0', '1527,0', '1866,0', '2026,0', '107,0', '170,0', '215,0', '304,0', '529,0', '691,0', '692,0', '1005,0', '1024,0', '1039,0', '1225,0', '1375,0', '1661,0', '1668,0', '1698,0', '1937,0', '2017,0', '117,0', '131,0', '153,0', '307,0', '374,0', '524,0', '569,0', '899,0', '1014,0', '1117,0', '1238,0', '1277,0', '1541,0', '1666,0', '1696,0', '1805,0', '1932,0', '2016,0', '20,0', '184,0', '206,0', '228,0', '239,0', '256,0', '339,0', '406,0', '429,0', '444,0', '452,0', '456,0', '481,0', '513,0', '597,0', '600,0', '630,0', '638,0', '683,0', '780,0', '817,0', '901,0', '944,0', '984,0', '1088,0', '1124,0', '1167,0', '1184,0', '1252,0', '1267,0', '1278,0', '1288,0', '1307,0', '1336,0', '1352,0', '

In [22]:
Over18_dict= list(df['Over18'].unique())
print(Over18_dict)

['Y', nan]


In [23]:
overtime_dict=list (df["OverTime"].unique())
print(overtime_dict)

['No', nan, 'Yes']


In [24]:
over18_dict=list (df["Over18"].unique())
print(over18_dict)

['Y', nan]


In [25]:
PerformanceRating_dic=list (df["PerformanceRating"].unique())
print(PerformanceRating_dic)

['3,0', '4,0', nan]


In [26]:
RelationshipSatisfaction_dic=list (df["RelationshipSatisfaction"].unique())
RelationshipSatisfaction_dic
df["RelationshipSatisfaction"].unique()

array([3, 1, 4, 2], dtype=int64)

In [27]:
StockOptionLevel_dic=list (df["StockOptionLevel"].unique())
StockOptionLevel_dic
df["StockOptionLevel"].unique()

array([0, 1, 2, 3], dtype=int64)

In [28]:
TOTALWORKINGYEARS_dic=list (df["TOTALWORKINGYEARS"].unique())
df["TOTALWORKINGYEARS"].unique()

array([nan, '34,0', '22,0', '28,0', '20,0', '21,0', '33,0', '40,0',
       '18,0', '25,0', '15,0', '17,0', '26,0', '16,0', '24,0', '14,0',
       '23,0', '27,0', '19,0', '11,0', '38,0', '37,0', '13,0', '12,0',
       '29,0', '10,0', '36,0', '35,0', '9,0', '31,0', '32,0', '8,0',
       '7,0', '30,0', '6,0', '5,0', '4,0', '3,0', '2,0', '1,0', '0,0'],
      dtype=object)

In [29]:
TrainingTimesLastYear_dic=list (df["TrainingTimesLastYear"].unique())
print(TrainingTimesLastYear_dic)
df["TrainingTimesLastYear"].unique()

[5, 3, 2, 0, 1, 4, 6]


array([5, 3, 2, 0, 1, 4, 6], dtype=int64)

In [30]:
WORKLIFEBALANCE_dic=list (df["WORKLIFEBALANCE"].unique())
df["WORKLIFEBALANCE"].unique()
print(WORKLIFEBALANCE_dic)

['3,0', nan, '2,0', '4,0', '1,0']


In [31]:
YearsAtCompany_dic=list (df["YearsAtCompany"].unique())
df["YearsAtCompany"].unique()

array([20, 33, 22, 19, 21, 18, 24, 31, 26, 16, 23, 15, 17, 32, 14, 13, 25,
       12, 11, 37, 40, 36, 27, 29, 10,  9, 30,  8,  7, 34,  6,  5,  4,  2,
        3,  1,  0], dtype=int64)

In [32]:
YearsSinceLastPromotion_dic=list (df["YearsSinceLastPromotion"].unique())
df["YearsSinceLastPromotion"].unique()

array([15, 11,  5,  2,  4,  7,  0,  1, 13, 14,  8, 12,  3,  6, 10,  9],
      dtype=int64)

In [33]:
YEARSWITHCURRMANAGER_dic=list (df["YEARSWITHCURRMANAGER"].unique())
print(YEARSWITHCURRMANAGER_dic)
df["YEARSWITHCURRMANAGER"].unique()

[15, 9, 6, 8, 7, 11, 10, 12, 4, 0, 5, 17, 2, 14, 1, 13, 3, 16]


array([15,  9,  6,  8,  7, 11, 10, 12,  4,  0,  5, 17,  2, 14,  1, 13,  3,
       16], dtype=int64)

In [34]:
SameAsMonthlyIncome_dic=list (df["SameAsMonthlyIncome"].unique())
print(SameAsMonthlyIncome_dic)
df["SameAsMonthlyIncome"].unique()

['19537,0', '19999,0', '19232,0', '17169,0', nan, '17174,0', '16595,0', '19973,0', '13402,0', '13206,0', '19545,0', '18041,0', '19246,0', '10748,0', '16752,0', '6201,0', '19845,0', '4001,0', '10447,0', '16064,0', '3210,0', '10266,0', '10475,0', '6162,0', '4721,0', '4615,0', '16959,0', '10306,0', '5406,0', '5902,0', '10855,0', '5914,0', '6646,0', '13973,0', '13320,0', '6687,0', '4735,0', '13872,0', '19045,0', '16015,0', '9613,0', '11510,0', '4306,0', '17046,0', '5067,0', '3692,0', '19847,0', '2308,0', '5747,0', '10422,0', '6347,0', '2348,0', '3072,0', '12490,0', '8020,0', '17068,0', '8943,0', '19272,0', '5577,0', '2691,0', '7403,0', '8823,0', '3579,0', '17779,0', '18213,0', '13577,0', '19190,0', '17123,0', '19187,0', '10008,0', '7988,0', '7083,0', '4723,0', '3407,0', '2929,0', '12031,0', '15427,0', '5126,0', '9619,0', '5010,0', '19033,0', '10400,0', '2793,0', '5674,0', '19197,0', '8412,0', '3348,0', '5309,0', '7654,0', '12808,0', '6586,0', '2519,0', '17099,0', '13120,0', '3131,0', '4444

array(['19537,0', '19999,0', '19232,0', '17169,0', nan, '17174,0',
       '16595,0', '19973,0', '13402,0', '13206,0', '19545,0', '18041,0',
       '19246,0', '10748,0', '16752,0', '6201,0', '19845,0', '4001,0',
       '10447,0', '16064,0', '3210,0', '10266,0', '10475,0', '6162,0',
       '4721,0', '4615,0', '16959,0', '10306,0', '5406,0', '5902,0',
       '10855,0', '5914,0', '6646,0', '13973,0', '13320,0', '6687,0',
       '4735,0', '13872,0', '19045,0', '16015,0', '9613,0', '11510,0',
       '4306,0', '17046,0', '5067,0', '3692,0', '19847,0', '2308,0',
       '5747,0', '10422,0', '6347,0', '2348,0', '3072,0', '12490,0',
       '8020,0', '17068,0', '8943,0', '19272,0', '5577,0', '2691,0',
       '7403,0', '8823,0', '3579,0', '17779,0', '18213,0', '13577,0',
       '19190,0', '17123,0', '19187,0', '10008,0', '7988,0', '7083,0',
       '4723,0', '3407,0', '2929,0', '12031,0', '15427,0', '5126,0',
       '9619,0', '5010,0', '19033,0', '10400,0', '2793,0', '5674,0',
       '19197,0', '841

In [35]:
DateBirth_dic=list (df["DateBirth"].unique())
print(DateBirth_dic)

df["DateBirth"].unique()

[1972, 1971, 1981, 1976, 1977, 1975, 1964, 1982, 1967, 1985, 1968, 1983, 1965, 1988, 1978, 1990, 1987, 1989, 1970, 1980, 1963, 1991, 1986, 1974, 1984, 1973, 1979, 1993, 1994, 1992, 1969, 1966, 1996, 1995, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005]


array([1972, 1971, 1981, 1976, 1977, 1975, 1964, 1982, 1967, 1985, 1968,
       1983, 1965, 1988, 1978, 1990, 1987, 1989, 1970, 1980, 1963, 1991,
       1986, 1974, 1984, 1973, 1979, 1993, 1994, 1992, 1969, 1966, 1996,
       1995, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005],
      dtype=int64)

In [36]:
Salary_dic=list (df["Salary"].unique())
print(Salary_dic)

df["Salary"].unique()

['1000000000$']


array(['1000000000$'], dtype=object)

In [37]:
NUMCOMPANIESWORKED_dic=list (df["NUMCOMPANIESWORKED"].unique())
print(NUMCOMPANIESWORKED_dic)

df["NUMCOMPANIESWORKED"].unique()

[7, 0, 1, 3, 2, 4, 8, 9, 5, 6]


array([7, 0, 1, 3, 2, 4, 8, 9, 5, 6], dtype=int64)

In [38]:
NUMBERCHILDREN_dic=list (df["NUMBERCHILDREN"].unique())
print(NUMBERCHILDREN_dic)


df["NUMBERCHILDREN"].unique()

[nan]


array([nan])

In [39]:
print(df['WORKLIFEBALANCE'].dtype) # es object
df['WORKLIFEBALANCE'].unique() #tiene valores nulos

object


array(['3,0', nan, '2,0', '4,0', '1,0'], dtype=object)

In [40]:
print(df['YearsAtCompany'].dtype) #es intiger
df['YearsAtCompany'].unique() 

int64


array([20, 33, 22, 19, 21, 18, 24, 31, 26, 16, 23, 15, 17, 32, 14, 13, 25,
       12, 11, 37, 40, 36, 27, 29, 10,  9, 30,  8,  7, 34,  6,  5,  4,  2,
        3,  1,  0], dtype=int64)

In [41]:
print(df['YearsInCurrentRole'].dtype) #es object
df['YearsInCurrentRole'].unique() #tiene valores nan

object


array([nan, '13,0', '12,0', '11,0', '7,0', '6,0', '4,0', '3,0', '2,0',
       '1,0', '0,0'], dtype=object)

In [73]:
print(df['StandardHours'].dtype) #es object
df['StandardHours'].unique() #tiene valores nan

object


array([nan, '80,0'], dtype=object)

In [42]:
print(df['YearsSinceLastPromotion'].dtype) # es intiger
df['YearsSinceLastPromotion'].unique() 

int64


array([15, 11,  5,  2,  4,  7,  0,  1, 13, 14,  8, 12,  3,  6, 10,  9],
      dtype=int64)

In [43]:
print(df['YEARSWITHCURRMANAGER'].dtype) #es intiger
df['YEARSWITHCURRMANAGER'].unique() 

int64


array([15,  9,  6,  8,  7, 11, 10, 12,  4,  0,  5, 17,  2, 14,  1, 13,  3,
       16], dtype=int64)

In [44]:
print(df['SameAsMonthlyIncome'].dtype) # es de tipo object
df['SameAsMonthlyIncome'].unique() # contiene nan

object


array(['19537,0', '19999,0', '19232,0', '17169,0', nan, '17174,0',
       '16595,0', '19973,0', '13402,0', '13206,0', '19545,0', '18041,0',
       '19246,0', '10748,0', '16752,0', '6201,0', '19845,0', '4001,0',
       '10447,0', '16064,0', '3210,0', '10266,0', '10475,0', '6162,0',
       '4721,0', '4615,0', '16959,0', '10306,0', '5406,0', '5902,0',
       '10855,0', '5914,0', '6646,0', '13973,0', '13320,0', '6687,0',
       '4735,0', '13872,0', '19045,0', '16015,0', '9613,0', '11510,0',
       '4306,0', '17046,0', '5067,0', '3692,0', '19847,0', '2308,0',
       '5747,0', '10422,0', '6347,0', '2348,0', '3072,0', '12490,0',
       '8020,0', '17068,0', '8943,0', '19272,0', '5577,0', '2691,0',
       '7403,0', '8823,0', '3579,0', '17779,0', '18213,0', '13577,0',
       '19190,0', '17123,0', '19187,0', '10008,0', '7988,0', '7083,0',
       '4723,0', '3407,0', '2929,0', '12031,0', '15427,0', '5126,0',
       '9619,0', '5010,0', '19033,0', '10400,0', '2793,0', '5674,0',
       '19197,0', '841

In [45]:
print(df['DateBirth'].dtype) # es de tipo intiger
df['DateBirth'].unique() 

int64


array([1972, 1971, 1981, 1976, 1977, 1975, 1964, 1982, 1967, 1985, 1968,
       1983, 1965, 1988, 1978, 1990, 1987, 1989, 1970, 1980, 1963, 1991,
       1986, 1974, 1984, 1973, 1979, 1993, 1994, 1992, 1969, 1966, 1996,
       1995, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005],
      dtype=int64)

In [46]:
print(df['Salary'].dtype)
df['Salary'].unique() #todos los valores son iguales, elimlinamos columna?

object


array(['1000000000$'], dtype=object)

In [47]:
print(df['RoleDepartament'].dtype) # tipo object
df['RoleDepartament'].unique() # contiene nan, también habría que corregir los nombres

object


array([nan, ' ManaGER  -  Research & Development ',
       ' MANAger  -  Research & Development ',
       ' heaLtHcArE repResENtATiVe  -  Research & Development ',
       ' saLEs exEcutIVe  -  Sales ', ' Sales ExECuTIVe  -  Sales ',
       ' heALthCArE RePResEntaTIVe  -  Research & Development ',
       ' lABORAtOry tECHnIcIan  -  Research & Development ',
       ' ManufactUrINg DiReCTOr  -  Research & Development ',
       ' SaleS eXEcUtIVE  -  Sales ',
       ' HEaLthcaRe rEprEsEnTAtiVe  -  Research & Development ',
       ' rESeArCH sCientIST  -  Research & Development ',
       ' healTHCAre rePREseNtATiVE  -  Research & Development ',
       ' mANaGer  -  Research & Development ',
       ' HEAltHCaRe REPreseNTatIve  -  Research & Development ',
       ' SaLeS eXECUTivE  -  Sales ',
       ' reSeARCH SCIEnTiST  -  Research & Development ',
       ' ReSearch DiRecTOR  -  Research & Development ',
       ' resEaRCh SciEnTist  -  Research & Development ',
       ' hUmaN REsoUrCes  -  H

In [48]:
print(df['NUMBERCHILDREN'].dtype) # tipo decimales
df['NUMBERCHILDREN'].unique() # todos los valores son nan, eliminamos la columna?

float64


array([nan])

In [49]:
print(df['RemoteWork'].dtype) # tipo object
df['RemoteWork'].unique() # unificar criterios

object


array(['Yes', '1', 'False', '0', 'True'], dtype=object)

# Columnas del indice 11 al 20

In [50]:
#Creo un sub data frame con las columnas que quiero mirar
subset_df = df.iloc[:, 11:21] 
subset_df

EnvironmentSatisfaction  Gender HourlyRate  JobInvolvement  JobLevel  \
0                           1       0         51               3         5   
1                           3       0         65               2         5   
2                           3       0         58               3         5   
3                           1       1         82               3         4   
4                           1       1         45               4         4   
...                       ...     ...        ...             ...       ...   
1609                        3       0         51               2         3   
1610                        3       0         57               3         2   
1611                       13       0         41               4         3   
1612                        1       0         84               3         2   
1613                        4       0         75               3         3   

                       JobRole  JobSatisfaction MaritalStatus MonthlyIncome  \
0           resEArch DIREcToR                 3           NaN       19537,0   
1                     ManAGeR                 3           NaN       19999,0   
2                     ManaGER                 4       Married       19232,0   
3           ReseArCH DIrECtOr                 3       Married       17169,0   
4             sAleS EXECUtIve                 1      Divorced           NaN   
...                        ...              ...           ...           ...   
1609          saLEs ExeCUTiVe                 4       Married       10325,0   
1610    LAboRaTOry tECHNiCIAn                 2           NaN        4447,0   
1611          sAlES ExECUTivE                 3        Single           NaN   
1612          SaLes ExecUtIVe                 4      Divorced           NaN   
1613   mAnUfactURInG DiRECTOr                 3           NaN       10845,0   

      MonthlyRate  
0            6462  
1            5678  
2            4933  
3           26703  
4            7739  
...           ...  
1609         5518  
1610        23163  
1611         2560  
1612        25952  
1613        24208  

[1614 rows x 10 columns]

In [51]:
# Calcular el número de valores nulos en la columna 'mi_columna'
def nulos(data, columna):
    nulos_en_columna = data[columna].isnull().sum()
    return nulos_en_columna

In [52]:
# Encontrar valores nulos
def indices_nulos (df):
    null_values = df.isnull()
    # Usar iloc para encontrar las posiciones de los valores nulos
    for i in range(len(df)):
        for j in range(len(df.columns)):
            if null_values.iloc[i, j]:
                print(f'Valor nulo encontrado en fila {i}, columna {df.columns[j]}')

Miramos cuantos valores nulos hay por columna

In [53]:
nulos_Enviro = nulos (subset_df, ['EnvironmentSatisfaction'])
nulos_Enviro

EnvironmentSatisfaction    0
dtype: int64

In [54]:
nulos_gender = nulos(subset_df, ['Gender'])
nulos_gender

Gender    0
dtype: int64

In [55]:
nulos_HourlyRate = nulos(subset_df, ['HourlyRate'])
nulos_HourlyRate

HourlyRate    0
dtype: int64

In [56]:
nulos_JobInvolvement = nulos(subset_df, ['JobInvolvement'])
nulos_JobInvolvement

JobInvolvement    0
dtype: int64

In [57]:
nulos_JobLevel = nulos(subset_df, ['JobLevel'])
nulos_JobLevel

JobLevel    0
dtype: int64

In [58]:
nulos_JobRole = nulos(subset_df, ['JobRole'])
nulos_JobRole

JobRole    0
dtype: int64

In [59]:
nulos_JobSatisfaction= nulos(subset_df, ['JobSatisfaction'])
nulos_JobSatisfaction

JobSatisfaction    0
dtype: int64

In [60]:
nulos_marital = nulos (subset_df, ['MaritalStatus'])
nulos_marital

MaritalStatus    651
dtype: int64

In [61]:
nulos_income = nulos(subset_df, ['MonthlyIncome'])
nulos_income

MonthlyIncome    843
dtype: int64

In [62]:
nulos_rate = nulos(subset_df, ['MonthlyRate'])
nulos_rate

MonthlyRate    0
dtype: int64

Miramos algunas de las columnas y sus valores

In [63]:
subset_df["MaritalStatus"].unique()

array([nan, 'Married', 'Divorced', 'Single', 'divorced', 'Marreid'],
      dtype=object)

In [64]:
subset_df["JobRole"].unique()
#JobRole hay distintas formas de nombrar los roles, con errores, ademas de minusculas y mayusculas

array([' resEArch DIREcToR ', ' ManAGeR ', ' ManaGER ', ...,
       ' sAlES ExECUTivE ', ' SaLes ExecUtIVe ',
       ' mAnUfactURInG DiRECTOr '], dtype=object)

In [65]:
subset_df["JobLevel"].unique()

array([5, 4, 3, 2, 1], dtype=int64)

In [66]:
subset_df["MonthlyRate"].unique()

array([ 6462,  5678,  4933, ..., 15302, 26956, 16642], dtype=int64)

# 2. Eliminacion de columnas que no vamos a usar

In [ ]:
#Estas son las columnas que vamos a eliminar

 
'employeecount' # Porque siempre es el mismo valor y es un contador de los empleados
'Over18' # Porque ya tenemos la edad y tiene muchos valores perdidos
'StandardHours' # Porque todos tienen el mismo valor que es 80 y ademas tienen muchos valores perdidos
'Salary' # Porque es igual a 10000000$ en todos los valores del dataframe
'NUMBERCHILDREN' # Porque no tiene ningun valor y es todo con valores missing.


In [80]:
df_nuevo=df.drop(columns=["employeecount", "Over18", "StandardHours","Salary", "NUMBERCHILDREN"],inplace=True )
df_nuevo.columns

KeyError: "['employeecount', 'Over18', 'StandardHours', 'Salary', 'NUMBERCHILDREN'] not found in axis"

In [72]:
df.columns


Index(['Unnamed: 0', 'Age', 'Attrition', 'BusinessTravel', 'DailyRate',
       'Department', 'DistanceFromHome', 'Education', 'EducationField',
       'employeecount', 'employeenumber', 'EnvironmentSatisfaction', 'Gender',
       'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole',
       'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'MonthlyRate',
       'NUMCOMPANIESWORKED', 'Over18', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours',
       'StockOptionLevel', 'TOTALWORKINGYEARS', 'TrainingTimesLastYear',
       'WORKLIFEBALANCE', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YEARSWITHCURRMANAGER',
       'SameAsMonthlyIncome', 'DateBirth', 'Salary', 'RoleDepartament',
       'NUMBERCHILDREN', 'RemoteWork'],
      dtype='object')