In [4]:
import numpy as np
import pandas as pd

# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

# Punto --> Exploración de los datos! ✅

In [5]:
df = pd.read_csv('df_limpio.csv', index_col= 0)
df.head()

age attrition businesstravel  dailyrate                department  \
unnamed: 0                                                                      
0            51        No            NaN      684.0                       NaN   
1            52        No            NaN      699.0                       NaN   
2            42        No  travel rarely      532.0   research & development    
3            47        No  travel rarely      359.0                       NaN   
4            46        No            NaN     1319.0                       NaN   

            distancefromhome  education    educationfield employeenumber  \
unnamed: 0                                                                 
0                          6          3               NaN          162,0   
1                          1          4     life sciences          259,0   
2                          4          2  technical degree          319,0   
3                          2          4           medical            NaN   
4                          3          3  technical degree            NaN   

            environmentsatisfaction  gender hourlyrate  jobinvolvement  \
unnamed: 0                                                               
0                                 1    Male         51               3   
1                                 3    Male         65               2   
2                                 3    Male         58               3   
3                                 1  Female         82               3   
4                                 1  Female         45               4   

            joblevel              jobrole  jobsatisfaction maritalstatus  \
unnamed: 0                                                                 
0                  5   research director                 3           NaN   
1                  5             manager                 3           NaN   
2                  5             manager                 4       Married   
3                  4   research director                 3       Married   
4                  4     sales executive                 1      Divorced   

           monthlyincome  monthlyrate  numcompaniesworked overtime  \
unnamed: 0                                                           
0                19537,0         6462                   7       No   
1                19999,0         5678                   0      NaN   
2                19232,0         4933                   1       No   
3                17169,0        26703                   3      NaN   
4                    NaN         7739                   2       No   

            percentsalaryhike performancerating  relationshipsatisfaction  \
unnamed: 0                                                                  
0                          13               3,0                         3   
1                          14               3,0                         1   
2                          11               3,0                         4   
3                          19               3,0                         2   
4                          12               3,0                         4   

            stockoptionlevel totalworkingyears  trainingtimeslastyear  \
unnamed: 0                                                              
0                          0               NaN                      5   
1                          1              34,0                      5   
2                          0              22,0                      3   
3                          2               NaN                      2   
4                          1               NaN                      5   

           worklifebalance  yearsatcompany yearsincurrentrole  \
unnamed: 0                                                      
0                      3,0              20                NaN   
1                      3,0              33                NaN   
2                      NaN              22              

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1614 entries, 0 to 1613
Data columns (total 36 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   age                       1614 non-null   int64  
 1   attrition                 1614 non-null   object 
 2   businesstravel            842 non-null    object 
 3   dailyrate                 1490 non-null   float64
 4   department                302 non-null    object 
 5   distancefromhome          1614 non-null   int64  
 6   education                 1614 non-null   int64  
 7   educationfield            869 non-null    object 
 8   employeenumber            1183 non-null   object 
 9   environmentsatisfaction   1614 non-null   int64  
 10  gender                    1614 non-null   object 
 11  hourlyrate                1614 non-null   object 
 12  jobinvolvement            1614 non-null   int64  
 13  joblevel                  1614 non-null   int64  
 14  jobrole      

In [4]:
df.columns

Index(['Unnamed: 0', 'Age', 'Attrition', 'BusinessTravel', 'DailyRate',
       'Department', 'DistanceFromHome', 'Education', 'EducationField',
       'employeecount', 'employeenumber', 'EnvironmentSatisfaction', 'Gender',
       'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole',
       'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'MonthlyRate',
       'NUMCOMPANIESWORKED', 'Over18', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours',
       'StockOptionLevel', 'TOTALWORKINGYEARS', 'TrainingTimesLastYear',
       'WORKLIFEBALANCE', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YEARSWITHCURRMANAGER',
       'SameAsMonthlyIncome', 'DateBirth', 'Salary', 'RoleDepartament',
       'NUMBERCHILDREN', 'RemoteWork'],
      dtype='object')

In [5]:
df.dtypes

Unnamed: 0                    int64
Age                          object
Attrition                    object
BusinessTravel               object
DailyRate                    object
Department                   object
DistanceFromHome              int64
Education                     int64
EducationField               object
employeecount                 int64
employeenumber               object
EnvironmentSatisfaction       int64
Gender                        int64
HourlyRate                   object
JobInvolvement                int64
JobLevel                      int64
JobRole                      object
JobSatisfaction               int64
MaritalStatus                object
MonthlyIncome                object
MonthlyRate                   int64
NUMCOMPANIESWORKED            int64
Over18                       object
OverTime                     object
PercentSalaryHike             int64
PerformanceRating            object
RelationshipSatisfaction      int64
StandardHours               

In [6]:
df.isnull().sum()

Unnamed: 0                     0
Age                            0
Attrition                      0
BusinessTravel               772
DailyRate                      0
Department                  1312
DistanceFromHome               0
Education                      0
EducationField               745
employeecount                  0
employeenumber               431
EnvironmentSatisfaction        0
Gender                         0
HourlyRate                     0
JobInvolvement                 0
JobLevel                       0
JobRole                        0
JobSatisfaction                0
MaritalStatus                651
MonthlyIncome                843
MonthlyRate                    0
NUMCOMPANIESWORKED             0
Over18                       901
OverTime                     676
PercentSalaryHike              0
PerformanceRating            195
RelationshipSatisfaction       0
StandardHours               1195
StockOptionLevel               0
TOTALWORKINGYEARS            526
TrainingTi

In [6]:
registro = df.shape
registro

(1614, 36)

In [7]:
df.isnull().sum()/registro[0]

age                         0.000000
attrition                   0.000000
businesstravel              0.478315
dailyrate                   0.076828
department                  0.812887
distancefromhome            0.000000
education                   0.000000
educationfield              0.461586
employeenumber              0.267038
environmentsatisfaction     0.000000
gender                      0.000000
hourlyrate                  0.000000
jobinvolvement              0.000000
joblevel                    0.000000
jobrole                     0.000000
jobsatisfaction             0.000000
maritalstatus               0.403346
monthlyincome               0.522305
monthlyrate                 0.000000
numcompaniesworked          0.000000
overtime                    0.418835
percentsalaryhike           0.000000
performancerating           0.120818
relationshipsatisfaction    0.000000
stockoptionlevel            0.000000
totalworkingyears           0.325898
trainingtimeslastyear       0.000000
w

# Punto --> Revisión de cada columna y las recomendaciones de transformación

In [ ]:
 
'Age' # Cambiar los años que estan en letras a números y volverlo todo int
'Attrition' # OK
'BusinessTravel' # revisar los NAN, Eliminarlos
'DailyRate' # OK
'Department' # revisar los NAN, Eliminarlos
'DistanceFromHome' # Revisar porque son (-)negativos y otros (+)positivos 
'Education' # OK
'EducationField' # Revisar los NAN
'employeecount' # Ok 
'employeenumber' # duplicados

'EnvironmentSatisfaction' # Ok 
'Gender' # Cambiar los valores, estan en 0 y 1 y hay que ponerlos M - F
'HourlyRate' # OK
'JobInvolvement' # OK
'JobLevel' # OK
'JobRole' # Cambiar palabras con minusculas y mayusculas 
'JobSatisfaction' # OK
'MaritalStatus' # revisar los NAN
'MonthlyIncome' # revisar los NAN
'MonthlyRate' # OK

'NUMCOMPANIESWORKED' # OK
'Over18' # revisar los NAN
'OverTime' # revisar los NAN
'PercentSalaryHike' # OK
'PerformanceRating' # revisar los NAN
'RelationshipSatisfaction' # OK
'StandardHours' # revisar los NAN
'StockOptionLevel' # OK
'TOTALWORKINGYEARS' # revisar los NAN
'TrainingTimesLastYear' # OK

'WORKLIFEBALANCE' # revisar los NAN
'YearsAtCompany' # OK
'YearsInCurrentRole' # revisar los NAN
'YearsSinceLastPromotion' # OK
'YEARSWITHCURRMANAGER' # OK
'SameAsMonthlyIncome' # revisar los NAN
'DateBirth' # OK
'Salary' # OK
'RoleDepartament' # revisar los NAN, y las mayus y minusculas tambien porque losnombre se repiten 
'NUMBERCHILDREN' # revisar los NAN
'RemoteWork' #  Revisa los False y los Trues porque solo hay SI

# Eliminar columnas 👌🏼 ✅

- `employeecount` # Porque siempre es el mismo valor y es un contador de los empleados
- `Over18` # Porque ya tenemos la edad y tiene muchos valores perdidos
- `StandardHours` # Porque todos tienen el mismo valor que es 80 y ademas tienen muchos valores perdidos
- `Salary` # Porque es igual a 10000000$ en todos los valores del dataframe
- `NUMBERCHILDREN` # Porque no tiene ningun valor y es todo con valores missing.

In [7]:
df.drop(["employeecount", "Over18", "StandardHours", "Salary", "NUMBERCHILDREN"], axis=1, inplace=True )

In [9]:
df.shape

(1614, 37)

----------

In [259]:
df.shape

(1614, 37)

### `Homogeneizamos el nombre de las columnas a minúsculas` ✅

In [11]:
# vamos a iterar por todas las columnas del DataFrame y a cada una de ellas la pondremos en minúsula y le aplicaremos un replace para quitar los puntos. 
nuevas_columnas = {columna: columna.lower() for columna in df.columns}

# comprobamos que hemos creado el diccionario correctamente
nuevas_columnas

{'Unnamed: 0': 'unnamed: 0',
 'Age': 'age',
 'Attrition': 'attrition',
 'BusinessTravel': 'businesstravel',
 'DailyRate': 'dailyrate',
 'Department': 'department',
 'DistanceFromHome': 'distancefromhome',
 'Education': 'education',
 'EducationField': 'educationfield',
 'employeenumber': 'employeenumber',
 'EnvironmentSatisfaction': 'environmentsatisfaction',
 'Gender': 'gender',
 'HourlyRate': 'hourlyrate',
 'JobInvolvement': 'jobinvolvement',
 'JobLevel': 'joblevel',
 'JobRole': 'jobrole',
 'JobSatisfaction': 'jobsatisfaction',
 'MaritalStatus': 'maritalstatus',
 'MonthlyIncome': 'monthlyincome',
 'MonthlyRate': 'monthlyrate',
 'NUMCOMPANIESWORKED': 'numcompaniesworked',
 'OverTime': 'overtime',
 'PercentSalaryHike': 'percentsalaryhike',
 'PerformanceRating': 'performancerating',
 'RelationshipSatisfaction': 'relationshipsatisfaction',
 'StockOptionLevel': 'stockoptionlevel',
 'TOTALWORKINGYEARS': 'totalworkingyears',
 'TrainingTimesLastYear': 'trainingtimeslastyear',
 'WORKLIFEBALANC

In [12]:
# una vez que tenemos el diccionario vamos a aplicar el método rename
df.rename(columns = nuevas_columnas, inplace = True)

# comprobamos que se han cambiado los nombres de las columnas
df.head()

unnamed: 0 age attrition businesstravel dailyrate  \
0           0  51        No            NaN    684,0$   
1           1  52        No            NaN    699,0$   
2           2  42        No  travel_rarely    532,0$   
3           3  47        No  travel_rarely    359,0$   
4           4  46        No            NaN   1319,0$   

                 department  distancefromhome  education    educationfield  \
0                       NaN                 6          3               NaN   
1                       NaN                 1          4     Life Sciences   
2   Research & Development                  4          2  Technical Degree   
3                       NaN                 2          4           Medical   
4                       NaN                 3          3  Technical Degree   

  employeenumber  ...  trainingtimeslastyear  worklifebalance yearsatcompany  \
0          162,0  ...                      5              3,0             20   
1          259,0  ...                      5              3,0             33   
2          319,0  ...                      3              NaN             22   
3            NaN  ...                      2              NaN             20   
4            NaN  ...                      5              3,0             19   

   yearsincurrentrole  yearssincelastpromotion yearswithcurrmanager  \
0                 NaN                       15                   15   
1                 NaN                       11                    9   
2                 NaN                       11                   15   
3                 NaN                        5                    6   
4                 NaN                        2                    8   

   sameasmonthlyincome datebirth                       roledepartament  \
0              19537,0      1972                                   NaN   
1              19999,0      1971                                   NaN   
2              19232,0      1981   ManaGER  -  Research & Development    
3              17169,0      1976                                   NaN   
4                  NaN      1977                                   NaN   

   remotework  
0         Yes  
1           1  
2           1  
3       False  
4           0  

[5 rows x 37 columns]

--------

# `Falta crear un code para eliminar los nulos o hacer promedios donde sea necesario. `

--------

- `Cambiamos las letras de números en la columna (age)` ✅
- `colocamos los datos de object a int` ✅
- Falta guerdarlo directamente en el dataframe 

In [14]:
df['age'].unique()

array(['51', '52', '42', '47', '46', '48', '59', '41', '56', '38', '55',
       '40', '58', '35', '45', '33', '36', '34', 'forty-seven', '53',
       '43', '60', '32', '37', '49', '39', '50', '44', '30',
       'fifty-eight', '29', '31', '54', '57', '27', 'thirty-six', '28',
       '26', 'fifty-five', '25', 'fifty-two', 'thirty-one', '24',
       'thirty', '23', '22', '21', '20', 'twenty-six', '19',
       'thirty-seven', '18', 'thirty-two', 'twenty-four'], dtype=object)

In [15]:
# Diccionario para convertir palabras a números
word_to_number = {
    'zero': 0, 'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five': 5,
    'six': 6, 'seven': 7, 'eight': 8, 'nine': 9, 'ten': 10, 'eleven': 11,
    'twelve': 12, 'thirteen': 13, 'fourteen': 14, 'fifteen': 15,
    'sixteen': 16, 'seventeen': 17, 'eighteen': 18, 'nineteen': 19,
    'twenty': 20, 'thirty': 30, 'forty': 40, 'fifty': 50, 'sixty': 60,
    'seventy': 70, 'eighty': 80, 'ninety': 90
}

# Función para convertir cadenas a números
def convert_to_number(age):
    try:
        # Primero intentamos convertir directamente a entero
        return int(age)
    except ValueError:
        # Si falla, intentamos convertir usando el diccionario
        words = age.split('-')
        number = 0
        for word in words:
            if word in word_to_number:
                number += word_to_number[word]
            else:
                return f"Error converting '{age}'"
        return number

# Aplicar la función de conversión a la columna 'Age' del DataFrame
df['age'] = df['age'].apply(convert_to_number)

# Verificar si hay errores en la conversión
errors = df['age'][df['age'].apply(lambda x: isinstance(x, str))]

# Mostrar los resultados
print("Converted Ages in DataFrame:")
print(df['age'].head())

if not errors.empty:
    print("\nErrors:")
    print(errors)
else:
    print("\nNo conversion errors.")


Converted Ages in DataFrame:
0    51
1    52
2    42
3    47
4    46
Name: age, dtype: int64

No conversion errors.


In [16]:
df['age'].unique()

array([51, 52, 42, 47, 46, 48, 59, 41, 56, 38, 55, 40, 58, 35, 45, 33, 36,
       34, 53, 43, 60, 32, 37, 49, 39, 50, 44, 30, 29, 31, 54, 57, 27, 28,
       26, 25, 24, 23, 22, 21, 20, 19, 18])

In [18]:
df['age'].shape

(1614,)

---------------

No requiere cambios ✅

In [20]:
df['attrition'].unique()

array(['No', 'Yes'], dtype=object)

---------

- `Separamos los string con espacio vacio('') y quitamos el (_)`✅
- `Eliminar los NAN`❓

In [22]:
df['businesstravel'].unique() 

array([nan, 'travel_rarely', 'travel_frequently', 'non-travel'],
      dtype=object)

In [27]:
df["businesstravel"] = df["businesstravel"].str.replace("_", " ").str.replace("-"," ")
df.sample(10)

unnamed: 0  age attrition     businesstravel dailyrate  \
1009        1009   56        No                NaN    718,0$   
1579        1579   34        No                NaN   1442,0$   
1595        1595   38        No                NaN    240,0$   
440          440   39        No                NaN   1387,0$   
73            73   38        No  travel frequently   1189,0$   
1610        1610   45        No         non travel    805,0$   
247          247   36        No                NaN   1383,0$   
301          301   29        No  travel frequently    442,0$   
879          879   23        No                NaN   1309,0$   
1230        1230   21        No      travel rarely    391,0$   

                    department  distancefromhome  education educationfield  \
1009                       NaN                 4          4            NaN   
1579                       NaN                 9          3        Medical   
1595                       NaN                 2          4  Life Sciences   
440    Research & Development                 10          5        Medical   
73                         NaN                 1          3  Life Sciences   
1610                       NaN                 4          2            NaN   
247                        NaN                10          3  Life Sciences   
301                        NaN                 2          2            NaN   
879                        NaN                26          1            NaN   
1230                       NaN                15          2            NaN   

     employeenumber  ...  trainingtimeslastyear  worklifebalance  \
1009            NaN  ...                      2              3,0   
1579          717,0  ...                      3              4,0   
1595          803,0  ...                      2              3,0   
440             NaN  ...                      3              3,0   
73           1668,0  ...                      4              NaN   
1610          972,0  ...                      5              2,0   
247          1790,0  ...                      1              3,0   
301           388,0  ...                      3              NaN   
879           465,0  ...                      2              2,0   
1230           30,0  ...                      6              3,0   

     yearsatcompany  yearsincurrentrole  yearssincelastpromotion  \
1009              5                 NaN                        4   
1579              8                 NaN                        7   
1595             15                 NaN                        4   
440               7                 NaN                        7   
73               13                 NaN                        2   
1610              9                 NaN                        0   
247              12                 NaN                        5   
301              10                 NaN                        0   
879               4                 NaN                        0   
1230              0                 NaN                        0   

     yearswithcurrmanager  sameasmonthlyincome datebirth  \
1009                    2                  NaN      1967   
1579                    7                  NaN      1989   
1595                   12               5980,0      1985   
440                     7                  NaN      1984   
73                      9               4735,0      1985   
1610                    8               4447,0      1978   
247                     7               8321,0      1987   
301                     9                  NaN      1994   
879                     2               2904,0      2000   
1230                    0                  NaN      2002   

                                        roledepartament  remotework  
1009                                                NaN        True  
1579                                                NaN         Yes  
1595                                                NaN       False  
440

--------

- `Cambiar a float`
- `Cambiar las comas(,) por puntos(.)`

In [29]:
df['dailyrate'].unique()

array(['684,0$', '699,0$', '532,0$', '359,0$', '1319,0$', '117,0$',
       '1435,0$', '635,0$', '1276,0$', '840,0$', '247,0$', '1369,0$',
       '201,0$', '1360,0$', '692,0$', '1398,0$', '286,0$', '1402,0$',
       '819,0$', '884,0$', '1238,0$', '515,0$', '1223,0$', '202,0$',
       '928,0$', '607,0$', '266,0$', '429,0$', '589,0$', 'nan$',
       '1180,0$', '1282,0$', '776,0$', '665,0$', '526,0$', '1034,0$',
       '1403,0$', '1499,0$', '580,0$', '859,0$', '263,0$', '1376,0$',
       '885,0$', '1003,0$', '1321,0$', '394,0$', '1372,0$', '1333,0$',
       '228,0$', '737,0$', '823,0$', '667,0$', '301,0$', '573,0$',
       '1329,0$', '630,0$', '1063,0$', '1017,0$', '1296,0$', '939,0$',
       '1355,0$', '1448,0$', '200,0$', '1202,0$', '404,0$', '208,0$',
       '813,0$', '465,0$', '1189,0$', '1001,0$', '1394,0$', '161,0$',
       '288,0$', '682,0$', '1354,0$', '147,0$', '119,0$', '1413,0$',
       '452,0$', '334,0$', '1132,0$', '982,0$', '480,0$', '1099,0$',
       '672,0$', '1379,0$', '58

In [50]:
df['dailyrate'] = df['dailyrate'].str.replace(",", ".").str.replace("$", "")
df['dailyrate'].unique()

array(['684.0', '699.0', '532.0', '359.0', '1319.0', '117.0', '1435.0',
       '635.0', '1276.0', '840.0', '247.0', '1369.0', '201.0', '1360.0',
       '692.0', '1398.0', '286.0', '1402.0', '819.0', '884.0', '1238.0',
       '515.0', '1223.0', '202.0', '928.0', '607.0', '266.0', '429.0',
       '589.0', 'nan', '1180.0', '1282.0', '776.0', '665.0', '526.0',
       '1034.0', '1403.0', '1499.0', '580.0', '859.0', '263.0', '1376.0',
       '885.0', '1003.0', '1321.0', '394.0', '1372.0', '1333.0', '228.0',
       '737.0', '823.0', '667.0', '301.0', '573.0', '1329.0', '630.0',
       '1063.0', '1017.0', '1296.0', '939.0', '1355.0', '1448.0', '200.0',
       '1202.0', '404.0', '208.0', '813.0', '465.0', '1189.0', '1001.0',
       '1394.0', '161.0', '288.0', '682.0', '1354.0', '147.0', '119.0',
       '1413.0', '452.0', '334.0', '1132.0', '982.0', '480.0', '1099.0',
       '672.0', '1379.0', '583.0', '1492.0', '1050.0', '469.0', '237.0',
       '1440.0', '1291.0', '1157.0', '1336.0', '1224.0',

In [51]:
df['dailyrate'] = df['dailyrate'].astype(float)

In [52]:
df.sample()

unnamed: 0  age attrition businesstravel  dailyrate  \
1249        1249   20       Yes            NaN      871.0   

                    department  distancefromhome  education educationfield  \
1249   research & development                  6          3  life sciences   

     employeenumber  ...  trainingtimeslastyear  worklifebalance  \
1249          137,0  ...                      5              3,0   

     yearsatcompany  yearsincurrentrole  yearssincelastpromotion  \
1249              1                 NaN                        1   

     yearswithcurrmanager  sameasmonthlyincome datebirth  \
1249                    0               2926,0      2003   

                                        roledepartament  remotework  
1249   LaBORatORy tEchNiCian  -  Research & Developm...       False  

[1 rows x 37 columns]

--------

- `Eliminar los NAN`❓
- `Cambiar a minúscula los datos`✅

In [35]:
df['department'].unique()

array([nan, ' Research & Development ', ' Sales ', ' Human Resources '],
      dtype=object)

In [36]:
df['department'] = df['department'].str.lower()
df.head()

unnamed: 0  age attrition businesstravel dailyrate  \
0           0   51        No            NaN    684.0$   
1           1   52        No            NaN    699.0$   
2           2   42        No  travel rarely    532.0$   
3           3   47        No  travel rarely    359.0$   
4           4   46        No            NaN   1319.0$   

                 department  distancefromhome  education    educationfield  \
0                       NaN                 6          3               NaN   
1                       NaN                 1          4     Life Sciences   
2   research & development                  4          2  Technical Degree   
3                       NaN                 2          4           Medical   
4                       NaN                 3          3  Technical Degree   

  employeenumber  ...  trainingtimeslastyear  worklifebalance yearsatcompany  \
0          162,0  ...                      5              3,0             20   
1          259,0  ...                      5              3,0             33   
2          319,0  ...                      3              NaN             22   
3            NaN  ...                      2              NaN             20   
4            NaN  ...                      5              3,0             19   

   yearsincurrentrole  yearssincelastpromotion yearswithcurrmanager  \
0                 NaN                       15                   15   
1                 NaN                       11                    9   
2                 NaN                       11                   15   
3                 NaN                        5                    6   
4                 NaN                        2                    8   

   sameasmonthlyincome datebirth                       roledepartament  \
0              19537,0      1972                                   NaN   
1              19999,0      1971                                   NaN   
2              19232,0      1981   ManaGER  -  Research & Development    
3              17169,0      1976                                   NaN   
4                  NaN      1977                                   NaN   

   remotework  
0         Yes  
1           1  
2           1  
3       False  
4           0  

[5 rows x 37 columns]

-----------

`Cambiar los números a positivos los que están negativos`✅

In [43]:
df['distancefromhome'] = df['distancefromhome'].abs()

In [44]:
df['distancefromhome'].unique()


array([ 6,  1,  4,  2,  3, 22, 25,  9,  7, 23, 10, 12, 14, 13, 15,  8, 42,
       28, 37,  5, 16, 35, 26, 24, 29, 17, 21, 18, 30, 27, 20, 31, 39, 11,
       19, 33, 34, 46, 36, 45, 47, 32, 41, 49, 48, 38, 43, 40, 44])

---------

No requiere cambios ✅

In [45]:
df['education'].unique()

array([3, 4, 2, 1, 5])

--------

- `cambiar a minúscula todo` ✅
- `Eliminar los NAN`

In [47]:
df['educationfield'] = df['educationfield'].str.lower()
df.head()

unnamed: 0  age attrition businesstravel dailyrate  \
0           0   51        No            NaN    684.0$   
1           1   52        No            NaN    699.0$   
2           2   42        No  travel rarely    532.0$   
3           3   47        No  travel rarely    359.0$   
4           4   46        No            NaN   1319.0$   

                 department  distancefromhome  education    educationfield  \
0                       NaN                 6          3               NaN   
1                       NaN                 1          4     life sciences   
2   research & development                  4          2  technical degree   
3                       NaN                 2          4           medical   
4                       NaN                 3          3  technical degree   

  employeenumber  ...  trainingtimeslastyear  worklifebalance yearsatcompany  \
0          162,0  ...                      5              3,0             20   
1          259,0  ...                      5              3,0             33   
2          319,0  ...                      3              NaN             22   
3            NaN  ...                      2              NaN             20   
4            NaN  ...                      5              3,0             19   

   yearsincurrentrole  yearssincelastpromotion yearswithcurrmanager  \
0                 NaN                       15                   15   
1                 NaN                       11                    9   
2                 NaN                       11                   15   
3                 NaN                        5                    6   
4                 NaN                        2                    8   

   sameasmonthlyincome datebirth                       roledepartament  \
0              19537,0      1972                                   NaN   
1              19999,0      1971                                   NaN   
2              19232,0      1981   ManaGER  -  Research & Development    
3              17169,0      1976                                   NaN   
4                  NaN      1977                                   NaN   

   remotework  
0         Yes  
1           1  
2           1  
3       False  
4           0  

[5 rows x 37 columns]

In [48]:
df['educationfield'].unique()

array([nan, 'life sciences', 'technical degree', 'medical', 'other',
       'marketing', 'human resources'], dtype=object)

--------

Eliminado ❌

In [ ]:
df['employeecount'].unique()

-------

`Eliminar duplicados`
Revisar bien cada registro para tomar una decisión

In [140]:
df['employeenumber'].unique()

array(['162,0', '259,0', '319,0', ..., '2012,0', '2023,0', '2040,0'],
      dtype=object)

In [243]:
df['employeenumber'].duplicated().sum()

534

In [245]:
df['employeenumber'].value_counts()

employeenumber
482,0     2
530,0     2
507,0     2
517,0     2
522,0     2
         ..
161,0     1
164,0     1
190,0     1
194,0     1
2040,0    1
Name: count, Length: 1079, dtype: int64

---------------------

No requiere cambios ✅

In [141]:
df['EnvironmentSatisfaction'].unique()

array([ 1,  3,  4,  2, 42, 37, 35, 25, 27, 31, 39, 21, 15, 14, 33, 19, 12,
       13, 28, 47, 36, 29, 24, 46, 16, 22, 41, 49, 11, 48, 18, 10, 45, 38,
       17, 20, 26, 43])

-------------

- `cambiar de 0 - 1 a Male/Female o M/F`✅
- `convertir en object ya que antes era int`✅


In [54]:
df['gender'] = df['gender'].replace({0: 'Male', 1: 'Female'})

In [55]:
df['gender'].unique()

array(['Male', 'Female'], dtype=object)

--------

- `Cambiar a formato de hora  o int`✅
- `Eliminar el Not Available`✅
- Volver a guardar en el dataframe, porque no estaba hecho

In [21]:
# Rellenar los valores NA con 0 o cualquier otro valor predeterminado
df['hourlyrate'] = df['hourlyrate'].fillna(0)


In [22]:

# Convertir la columna a enteros
df['hourlyrate'] = df['hourlyrate'].astype(int)

In [23]:
df['hourlyrate'].unique()

array([ 51,  65,  58,  82,  45,  99,  91,  64,  55,  68,  49,  61,  79,
        31,  69,  48,  80,  74,  98,  59,  33,  56,  66,  57,  53,  87,
        81,  84,  32,  41,  92,  47,   0,  43,  86,  30,  42,  88,  96,
        67,  62,  72,  78,  89,  52,  50,  90,  37,  94,  76,  60,  46,
        83, 100,  40,  97,  54,  75,  39,  85,  63,  44,  93,  36,  35,
        73,  71,  70,  38,  77,  95,  34])

------

No requiere cambios ✅

In [57]:
df['jobinvolvement'].unique()

array([3, 2, 4, 1])

-------

No requiere cambios ✅

In [58]:
df['joblevel'].unique()

array([5, 4, 3, 2, 1])

-----------

- `cambiar a minúsculas` ✅

In [62]:
df['jobrole'] = df['jobrole'].str.lower()

In [63]:
df['jobrole'].unique()

array([' research director ', ' manager ', ' sales executive ',
       ' manufacturing director ', ' research scientist ',
       ' healthcare representative ', ' laboratory technician ',
       ' sales representative ', ' human resources '], dtype=object)

-------

No requiere cambios ✅

In [64]:
df['jobsatisfaction'].unique()

array([3, 4, 1, 2])

-------

# DESDE AQUI FALTA REVISAR Y HACER LOS CAMBIOS
### `Recuerden comentar lo que se cambio.`

-------

- `cambiar a minúsculas` ✅
- `Eliminar los NAN`
- `Eliminar la plabras 'Marreid' ` ✅

In [34]:
df["maritalstatus"] = df["maritalstatus"].str.lower()
df["maritalstatus"] = df["maritalstatus"].str.replace('marreid', 'married')

In [35]:
df['maritalstatus'].unique()

array([nan, 'married', 'divorced', 'single'], dtype=object)

-------

- ` quitar las comas por puntos `
- `tiene NAN`

In [38]:
def cambiar_comas(cadena):
    try:
        return float(cadena.replace(',', '').replace('.', ''))
    except:
        return np.nan
df['monthlyincome'] = df['monthlyincome'].apply(cambiar_comas)

In [39]:
df['monthlyincome'].unique()

array([nan])

-------

No requiere cambios ✅

In [40]:
df['monthlyrate'].unique()

array([ 6462,  5678,  4933, ..., 15302, 26956, 16642])

-------------------------

No requiere cambios ✅

In [42]:
df["numcompaniesworked"].unique()

array([7, 0, 1, 3, 2, 4, 8, 9, 5, 6])

-------

Eliminado ❌

In [ ]:
df['Over18'].unique()

-------

`hay un 42% de nulos, quizás eliminarla? - Eliminar los NAN`

In [24]:
df['overtime'].isnull().sum()/df.shape[0]

0.4188351920693928

In [26]:
df["overtime"].unique()

array(['No', nan, 'Yes'], dtype=object)

-------

No requiere cambios ✅

In [30]:
df['percentsalaryhike'].unique()

array([13, 14, 11, 19, 12, 25, 16, 17, 22, 23, 20, 15, 21, 24, 18])

-------

- `volverlo int`
- `Eliminar los NAN `

In [29]:
df["performancerating"].unique()

array(['3,0', '4,0', nan], dtype=object)

-------

No requiere cambios ✅

In [28]:
df["relationshipsatisfaction"].unique()

array([3, 1, 4, 2])

-------

Eliminado ❌

In [ ]:
df["standardhours"].unique()

-------

No requiere cambios ✅

In [158]:
df["stockoptionlevel"].unique()

array([0, 1, 2, 3])

-------

- `Cambiar a int `
- `Eliminar los NAN `

In [33]:
df["totalworkingyears"].unique()

array([nan, '34,0', '22,0', '28,0', '20,0', '21,0', '33,0', '40,0',
       '18,0', '25,0', '15,0', '17,0', '26,0', '16,0', '24,0', '14,0',
       '23,0', '27,0', '19,0', '11,0', '38,0', '37,0', '13,0', '12,0',
       '29,0', '10,0', '36,0', '35,0', '9,0', '31,0', '32,0', '8,0',
       '7,0', '30,0', '6,0', '5,0', '4,0', '3,0', '2,0', '1,0', '0,0'],
      dtype=object)

-------

No requiere cambios ✅

In [44]:
df["trainingtimeslastyear"].unique()

array([5, 3, 2, 0, 1, 4, 6])

-----------

- `Tiene NAN`
- `cambiar a int`


In [45]:
df['worklifebalance'].unique()

array(['3,0', nan, '2,0', '4,0', '1,0'], dtype=object)

-------

No requiere cambios ✅

In [10]:
df['yearsatcompany'].unique()

array([20, 33, 22, 19, 21, 18, 24, 31, 26, 16, 23, 15, 17, 32, 14, 13, 25,
       12, 11, 37, 40, 36, 27, 29, 10,  9, 30,  8,  7, 34,  6,  5,  4,  2,
        3,  1,  0])

-------

- `cambiar a int`
- `Elimiar los NAN`
- `revisar si Eliminar la clumna porque tiene 90% null`

In [163]:
df['yearsincurrentrole'].unique()

array([nan, '13,0', '12,0', '11,0', '7,0', '6,0', '4,0', '3,0', '2,0',
       '1,0', '0,0'], dtype=object)

-------

No requiere cambios ✅

In [46]:
df['yearssincelastpromotion'].unique()

array([15, 11,  5,  2,  4,  7,  0,  1, 13, 14,  8, 12,  3,  6, 10,  9])

-------

No requiere cambios ✅

In [6]:
df['yearswithcurrmanager'].unique() 

array([15,  9,  6,  8,  7, 11, 10, 12,  4,  0,  5, 17,  2, 14,  1, 13,  3,
       16])

-------

- `Cambiar a int o float`
- `Tienen NAN`

In [7]:
df["sameasmonthlyincome"].unique()

array(['19537,0', '19999,0', '19232,0', '17169,0', nan, '17174,0',
       '16595,0', '19973,0', '13402,0', '13206,0', '19545,0', '18041,0',
       '19246,0', '10748,0', '16752,0', '6201,0', '19845,0', '4001,0',
       '10447,0', '16064,0', '3210,0', '10266,0', '10475,0', '6162,0',
       '4721,0', '4615,0', '16959,0', '10306,0', '5406,0', '5902,0',
       '10855,0', '5914,0', '6646,0', '13973,0', '13320,0', '6687,0',
       '4735,0', '13872,0', '19045,0', '16015,0', '9613,0', '11510,0',
       '4306,0', '17046,0', '5067,0', '3692,0', '19847,0', '2308,0',
       '5747,0', '10422,0', '6347,0', '2348,0', '3072,0', '12490,0',
       '8020,0', '17068,0', '8943,0', '19272,0', '5577,0', '2691,0',
       '7403,0', '8823,0', '3579,0', '17779,0', '18213,0', '13577,0',
       '19190,0', '17123,0', '19187,0', '10008,0', '7988,0', '7083,0',
       '4723,0', '3407,0', '2929,0', '12031,0', '15427,0', '5126,0',
       '9619,0', '5010,0', '19033,0', '10400,0', '2793,0', '5674,0',
       '19197,0', '841

-------

- `Cambiar dato a fecha año`


In [167]:
df["DateBirth"].unique()

array([1972, 1971, 1981, 1976, 1977, 1975, 1964, 1982, 1967, 1985, 1968,
       1983, 1965, 1988, 1978, 1990, 1987, 1989, 1970, 1980, 1963, 1991,
       1986, 1974, 1984, 1973, 1979, 1993, 1994, 1992, 1969, 1966, 1996,
       1995, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005])

-------

Eliminado ❌

In [ ]:
df["salary"].unique()

-------

- `Cambiar a minúsculas` ✅
- `Eliminar los NAN`
- `Eliminar la columna porque tiene muchos nulos`

In [8]:
df['roledepartament'] = df['roledepartament'].str.lower()

In [9]:
df['roledepartament'].unique()

array([nan, ' manager  -  research & development ',
       ' healthcare representative  -  research & development ',
       ' sales executive  -  sales ',
       ' laboratory technician  -  research & development ',
       ' manufacturing director  -  research & development ',
       ' research scientist  -  research & development ',
       ' research director  -  research & development ',
       ' human resources  -  human resources ', ' manager  -  sales ',
       ' sales representative  -  sales ',
       ' manager  -  human resources '], dtype=object)

------

Eliminado ❌

In [ ]:
df["numberchildren"].unique()

-------

- `Cambiar falso por No y True por Si`
- `eliminar Yes`
- `Revisar para cambiar los 1: por (Si o No) y los 0: por (Si o No). Dependiedo como interpretar esos dos valores`

In [67]:
df["remotework"].unique()

array(['Yes', '1', 'False', '0', 'True'], dtype=object)

-------

In [74]:
# Guarda el DataFrame como un archivo CSV
df.to_csv("df_limpio.csv", index = False)