In [70]:
#!pip install scikit-learn
#!pip install seaborn
#!pip install matplotlib

In [71]:
# importamos las librerías que necesitamos

# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np
import re

# Imputación de nulos usando métodos avanzados estadísticos
# -----------------------------------------------------------------------
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer

# Librerías de visualización
# -----------------------------------------------------------------------
import seaborn as sns
import matplotlib.pyplot as plt
# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

# Punto --> Exploración de los datos! ✅

In [72]:
df = pd.read_csv('../HR RAW DATA.csv', index_col= 0)
df.head()

Age Attrition BusinessTravel DailyRate                Department  \
0  51        No            NaN    684,0$                       NaN   
1  52        No            NaN    699,0$                       NaN   
2  42        No  travel_rarely    532,0$   Research & Development    
3  47        No  travel_rarely    359,0$                       NaN   
4  46        No            NaN   1319,0$                       NaN   

   DistanceFromHome  Education    EducationField  employeecount  \
0                 6          3               NaN              1   
1                 1          4     Life Sciences              1   
2                 4          2  Technical Degree              1   
3                 2          4           Medical              1   
4                 3          3  Technical Degree              1   

  employeenumber  EnvironmentSatisfaction  Gender HourlyRate  JobInvolvement  \
0          162,0                        1       0         51               3   
1          259,0                        3       0         65               2   
2          319,0                        3       0         58               3   
3            NaN                        1       1         82               3   
4            NaN                        1       1         45               4   

   JobLevel              JobRole  JobSatisfaction MaritalStatus MonthlyIncome  \
0         5   resEArch DIREcToR                 3           NaN       19537,0   
1         5             ManAGeR                 3           NaN       19999,0   
2         5             ManaGER                 4       Married       19232,0   
3         4   ReseArCH DIrECtOr                 3       Married       17169,0   
4         4     sAleS EXECUtIve                 1      Divorced           NaN   

   MonthlyRate  NUMCOMPANIESWORKED Over18 OverTime  PercentSalaryHike  \
0         6462                   7      Y       No                 13   
1         5678                   0    NaN      NaN                 14   
2         4933                   1    NaN       No                 11   
3        26703                   3      Y      NaN                 19   
4         7739                   2      Y       No                 12   

  PerformanceRating  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0               3,0                         3           NaN                 0   
1               3,0                         1           NaN                 1   
2               3,0                         4           NaN                 0   
3               3,0                         2           NaN                 2   
4               3,0                         4           NaN                 1   

  TOTALWORKINGYEARS  TrainingTimesLastYear WORKLIFEBALANCE  YearsAtCompany  \
0               NaN                      5             3,0              20   
1              34,0                      5             3,0              33   
2              22,0                      3             NaN              22   
3               NaN                      2             NaN              20   
4               NaN                      5             3,0              19   

  YearsInCurrentRole  YearsSinceLastPromotion  YEARSWITHCURRMANAGER  \
0                NaN                       15                    15   
1                NaN                       11                     9   
2                NaN                       11                    15   
3                NaN                        5                     6   
4                NaN                        2                     8   

  SameAsMonthlyIncome  DateBirth       Salary  \
0             19537,0       1972  1000000000$   
1             19999,0       1971  1000000000$   
2             19232,0       1981  1000000000$   
3             17169,0       1976  1000000000$   
4                 NaN       1977  1000000000$   

                        RoleDepartament  NUMBERCHILDREN RemoteWork  
0                       

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1614 entries, 0 to 1613
Data columns (total 41 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Age                       1614 non-null   object 
 1   Attrition                 1614 non-null   object 
 2   BusinessTravel            842 non-null    object 
 3   DailyRate                 1614 non-null   object 
 4   Department                302 non-null    object 
 5   DistanceFromHome          1614 non-null   int64  
 6   Education                 1614 non-null   int64  
 7   EducationField            869 non-null    object 
 8   employeecount             1614 non-null   int64  
 9   employeenumber            1183 non-null   object 
 10  EnvironmentSatisfaction   1614 non-null   int64  
 11  Gender                    1614 non-null   int64  
 12  HourlyRate                1614 non-null   object 
 13  JobInvolvement            1614 non-null   int64  
 14  JobLevel     

In [74]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'employeecount',
       'employeenumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NUMCOMPANIESWORKED',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TOTALWORKINGYEARS', 'TrainingTimesLastYear', 'WORKLIFEBALANCE',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YEARSWITHCURRMANAGER', 'SameAsMonthlyIncome', 'DateBirth', 'Salary',
       'RoleDepartament', 'NUMBERCHILDREN', 'RemoteWork'],
      dtype='object')

In [75]:
df.dtypes

Age                          object
Attrition                    object
BusinessTravel               object
DailyRate                    object
Department                   object
DistanceFromHome              int64
Education                     int64
EducationField               object
employeecount                 int64
employeenumber               object
EnvironmentSatisfaction       int64
Gender                        int64
HourlyRate                   object
JobInvolvement                int64
JobLevel                      int64
JobRole                      object
JobSatisfaction               int64
MaritalStatus                object
MonthlyIncome                object
MonthlyRate                   int64
NUMCOMPANIESWORKED            int64
Over18                       object
OverTime                     object
PercentSalaryHike             int64
PerformanceRating            object
RelationshipSatisfaction      int64
StandardHours                object
StockOptionLevel            

In [76]:
# Valores nulos del total dataframe por columnas
df.isnull().sum()

Age                            0
Attrition                      0
BusinessTravel               772
DailyRate                      0
Department                  1312
DistanceFromHome               0
Education                      0
EducationField               745
employeecount                  0
employeenumber               431
EnvironmentSatisfaction        0
Gender                         0
HourlyRate                     0
JobInvolvement                 0
JobLevel                       0
JobRole                        0
JobSatisfaction                0
MaritalStatus                651
MonthlyIncome                843
MonthlyRate                    0
NUMCOMPANIESWORKED             0
Over18                       901
OverTime                     676
PercentSalaryHike              0
PerformanceRating            195
RelationshipSatisfaction       0
StandardHours               1195
StockOptionLevel               0
TOTALWORKINGYEARS            526
TrainingTimesLastYear          0
WORKLIFEBA

In [77]:
porcentaje_nulos = df.isnull().mean() * 100

# df.isnull().sum()/registro[0] - Otra forma de hacerlo

# Muestra los resultados<z
porcentaje_nulos

Age                           0.000000
Attrition                     0.000000
BusinessTravel               47.831475
DailyRate                     0.000000
Department                   81.288724
DistanceFromHome              0.000000
Education                     0.000000
EducationField               46.158612
employeecount                 0.000000
employeenumber               26.703841
EnvironmentSatisfaction       0.000000
Gender                        0.000000
HourlyRate                    0.000000
JobInvolvement                0.000000
JobLevel                      0.000000
JobRole                       0.000000
JobSatisfaction               0.000000
MaritalStatus                40.334572
MonthlyIncome                52.230483
MonthlyRate                   0.000000
NUMCOMPANIESWORKED            0.000000
Over18                       55.824040
OverTime                     41.883519
PercentSalaryHike             0.000000
PerformanceRating            12.081784
RelationshipSatisfaction 

In [78]:
registro = df.shape
registro

(1614, 41)

# Punto --> Revisión de cada columna 👌🏼

In [79]:
 
'Age' # OK
'Attrition' # OK
'BusinessTravel' # revisar los NAN
'DailyRate' # OK
'Department' # ELIMINDADO
'DistanceFromHome' # OK
'Education' # OK
'EducationField' # Revisar los NAN
'employeecount' # Ok - ELIMINDADO
'employeenumber' # duplicados

'EnvironmentSatisfaction' # Ok 
'Gender' # # OK
'HourlyRate' # OK
'JobInvolvement' # OK
'JobLevel' # OK
'JobRole' # OK
'JobSatisfaction' # OK
'MaritalStatus' # revisar los NAN
'MonthlyIncome' # revisar los NAN
'MonthlyRate' # OK

'NUMCOMPANIESWORKED' # OK
'Over18' # ELIMINADO
'OverTime' # revisar los NAN
'PercentSalaryHike' # OK
'PerformanceRating' # revisar los NAN
'RelationshipSatisfaction' # OK
'StandardHours' # ELIMINADO
'StockOptionLevel' # OK
'TOTALWORKINGYEARS' # revisar los NAN
'TrainingTimesLastYear' # OK

'WORKLIFEBALANCE' # revisar los NAN
'YearsAtCompany' # OK
'YearsInCurrentRole' # ELIMINADO
'YearsSinceLastPromotion' # OK
'YEARSWITHCURRMANAGER' # OK
'SameAsMonthlyIncome' # ELIMINADO
'DateBirth' # OK
'Salary' # ELIMINADO
'RoleDepartament' # ELIMINADO
'NUMBERCHILDREN' # ELIMINADO
'RemoteWork' # OK

'RemoteWork'

# Eliminar columnas ✅

- `employeecount` # Porque siempre es el mismo valor y es un contador de los empleados
- `Department` # con un 81% de datos nulos y ya una columna en paralelo dice lo mismos datos
- `Over18` # Porque ya tenemos la edad y tiene muchos valores perdidos
- `StandardHours` # Porque todos tienen el mismo valor que es 80 y ademas tienen muchos valores perdidos
- `Salary` # Porque es igual a 10000000$ en todos los valores del dataframe
- `NUMBERCHILDREN` # Porque no tiene ningun valor y es todo con valores missing.
- `RoleDepartament` # con un 81% de datos nulos y ya una columna en paralelo dice lo mismos datos
- `YearsInCurrentRole` # 97% de nulos 
- `SameAsMonthlyIncome` # Contiene la misma informacion que MonthlyIncome, por lo tanto la eliminamos


In [80]:
df.drop(["employeecount", "Department", "Over18", "StandardHours","Salary", "NUMBERCHILDREN", "RoleDepartament", "YearsInCurrentRole","SameAsMonthlyIncome"], axis=1, inplace=True )

In [81]:
df.head(1)

Age Attrition BusinessTravel DailyRate  DistanceFromHome  Education  \
0  51        No            NaN    684,0$                 6          3   

  EducationField employeenumber  EnvironmentSatisfaction  Gender HourlyRate  \
0            NaN          162,0                        1       0         51   

   JobInvolvement  JobLevel              JobRole  JobSatisfaction  \
0               3         5   resEArch DIREcToR                 3   

  MaritalStatus MonthlyIncome  MonthlyRate  NUMCOMPANIESWORKED OverTime  \
0           NaN       19537,0         6462                   7       No   

   PercentSalaryHike PerformanceRating  RelationshipSatisfaction  \
0                 13               3,0                         3   

   StockOptionLevel TOTALWORKINGYEARS  TrainingTimesLastYear WORKLIFEBALANCE  \
0                 0               NaN                      5             3,0   

   YearsAtCompany  YearsSinceLastPromotion  YEARSWITHCURRMANAGER  DateBirth  \
0              20                       15                    15       1972   

  RemoteWork  
0        Yes

In [82]:
df.shape

(1614, 32)

----------

- `Homogeneizamos el nombre de las columnas a minúsculas` ✅

In [83]:
# vamos a iterar por todas las columnas del DataFrame y a cada una de ellas la pondremos en minúsula y le aplicaremos un replace para quitar los puntos. 
nuevas_columnas = {columna: columna.lower() for columna in df.columns}

# comprobamos que hemos creado el diccionario correctamente
nuevas_columnas

{'Age': 'age',
 'Attrition': 'attrition',
 'BusinessTravel': 'businesstravel',
 'DailyRate': 'dailyrate',
 'DistanceFromHome': 'distancefromhome',
 'Education': 'education',
 'EducationField': 'educationfield',
 'employeenumber': 'employeenumber',
 'EnvironmentSatisfaction': 'environmentsatisfaction',
 'Gender': 'gender',
 'HourlyRate': 'hourlyrate',
 'JobInvolvement': 'jobinvolvement',
 'JobLevel': 'joblevel',
 'JobRole': 'jobrole',
 'JobSatisfaction': 'jobsatisfaction',
 'MaritalStatus': 'maritalstatus',
 'MonthlyIncome': 'monthlyincome',
 'MonthlyRate': 'monthlyrate',
 'NUMCOMPANIESWORKED': 'numcompaniesworked',
 'OverTime': 'overtime',
 'PercentSalaryHike': 'percentsalaryhike',
 'PerformanceRating': 'performancerating',
 'RelationshipSatisfaction': 'relationshipsatisfaction',
 'StockOptionLevel': 'stockoptionlevel',
 'TOTALWORKINGYEARS': 'totalworkingyears',
 'TrainingTimesLastYear': 'trainingtimeslastyear',
 'WORKLIFEBALANCE': 'worklifebalance',
 'YearsAtCompany': 'yearsatcompany'

In [84]:
# una vez que tenemos el diccionario vamos a aplicar el método rename
df.rename(columns = nuevas_columnas, inplace = True)

# comprobamos que se han cambiado los nombres de las columnas
df.head()

age attrition businesstravel dailyrate  distancefromhome  education  \
0  51        No            NaN    684,0$                 6          3   
1  52        No            NaN    699,0$                 1          4   
2  42        No  travel_rarely    532,0$                 4          2   
3  47        No  travel_rarely    359,0$                 2          4   
4  46        No            NaN   1319,0$                 3          3   

     educationfield employeenumber  environmentsatisfaction  gender  \
0               NaN          162,0                        1       0   
1     Life Sciences          259,0                        3       0   
2  Technical Degree          319,0                        3       0   
3           Medical            NaN                        1       1   
4  Technical Degree            NaN                        1       1   

  hourlyrate  jobinvolvement  joblevel              jobrole  jobsatisfaction  \
0         51               3         5   resEArch DIREcToR                 3   
1         65               2         5             ManAGeR                 3   
2         58               3         5             ManaGER                 4   
3         82               3         4   ReseArCH DIrECtOr                 3   
4         45               4         4     sAleS EXECUtIve                 1   

  maritalstatus monthlyincome  monthlyrate  numcompaniesworked overtime  \
0           NaN       19537,0         6462                   7       No   
1           NaN       19999,0         5678                   0      NaN   
2       Married       19232,0         4933                   1       No   
3       Married       17169,0        26703                   3      NaN   
4      Divorced           NaN         7739                   2       No   

   percentsalaryhike performancerating  relationshipsatisfaction  \
0                 13               3,0                         3   
1                 14               3,0                         1   
2                 11               3,0                         4   
3                 19               3,0                         2   
4                 12               3,0                         4   

   stockoptionlevel totalworkingyears  trainingtimeslastyear worklifebalance  \
0                 0               NaN                      5             3,0   
1                 1              34,0                      5             3,0   
2                 0              22,0                      3             NaN   
3                 2               NaN                      2             NaN   
4                 1               NaN                      5             3,0   

   yearsatcompany  yearssincelastpromotion  yearswithcurrmanager  datebirth  \
0              20                       15                    15       1972   
1              33                       11                     9       1971   
2              22                       11                    15       1981   
3              20                        5                     6       1976   
4              19                        2                     8       1977   

  remotework  
0        Yes  
1          1  
2          1  
3      False  
4          0

--------

- `Cambiamos las letras de números en la columna (age)` ✅
- `colocamos los datos de object a int` ✅
- `Falta guerdarlo directamente en el dataframe` ✅

In [85]:
# Diccionario para convertir palabras a números
word_to_number = {
    'zero': 0, 'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five': 5,
    'six': 6, 'seven': 7, 'eight': 8, 'nine': 9, 'ten': 10, 'eleven': 11,
    'twelve': 12, 'thirteen': 13, 'fourteen': 14, 'fifteen': 15,
    'sixteen': 16, 'seventeen': 17, 'eighteen': 18, 'nineteen': 19,
    'twenty': 20, 'thirty': 30, 'forty': 40, 'fifty': 50, 'sixty': 60,
    'seventy': 70, 'eighty': 80, 'ninety': 90
}

# Función para convertir cadenas a números
def convert_to_number(age):
    try:
        # Primero intentamos convertir directamente a entero
        return int(age)
    except ValueError:
        # Si falla, intentamos convertir usando el diccionario
        words = age.split('-')
        number = 0
        for word in words:
            if word in word_to_number:
                number += word_to_number[word]
            else:
                return f"Error converting '{age}'"
        return number

# Aplicar la función de conversión a la columna 'Age' del DataFrame
df['age'] = df['age'].apply(convert_to_number)

# Verificar si hay errores en la conversión
errors = df['age'][df['age'].apply(lambda x: isinstance(x, str))]

# Mostrar los resultados
print("Converted Ages in DataFrame:")
print(df['age'].head())

if not errors.empty:
    print("\nErrors:")
    print(errors)
else:
    print("\nNo conversion errors.")


Converted Ages in DataFrame:
0    51
1    52
2    42
3    47
4    46
Name: age, dtype: int64

No conversion errors.


In [86]:
df['age'].unique()

array([51, 52, 42, 47, 46, 48, 59, 41, 56, 38, 55, 40, 58, 35, 45, 33, 36,
       34, 53, 43, 60, 32, 37, 49, 39, 50, 44, 30, 29, 31, 54, 57, 27, 28,
       26, 25, 24, 23, 22, 21, 20, 19, 18])

In [87]:
df['age'].shape

(1614,)

---------------

No requiere cambios ✅

In [88]:
df['attrition'].unique()

array(['No', 'Yes'], dtype=object)

---------

- `Separamos los string con espacio vacio('') y quitamos el (_)`✅
- `Eliminar los NAN`❓

In [89]:
df['businesstravel'].unique() 

array([nan, 'travel_rarely', 'travel_frequently', 'non-travel'],
      dtype=object)

In [90]:
df["businesstravel"] = df["businesstravel"].str.replace("_", " ").str.replace("-"," ")
df.sample(5)

age attrition businesstravel dailyrate  distancefromhome  education  \
962    24        No     non travel   1269,0$               -19          1   
578    37        No            NaN    228,0$                 6          4   
843    40        No            NaN    905,0$               -38          2   
1043   27        No            NaN      nan$                10          3   
1418   29        No            NaN    991,0$                 5          3   

     educationfield employeenumber  environmentsatisfaction  gender  \
962   Life Sciences          888,0                        1       0   
578             NaN          378,0                        3       0   
843             NaN            NaN                        3       0   
1043      Marketing         1403,0                        4       1   
1418            NaN         1669,0                        1       0   

         hourlyrate  jobinvolvement  joblevel                  jobrole  \
962   Not Available               2         1   labORatOry TEcHniCIAn    
578   Not Available               3         2         sALes EXECUTiVE    
843              99               3         2   lAborAToRY tEChnIciAN    
1043             98               2         2         SaleS ExECUTIvE    
1418             43               2         2         sAles exeCUTIvE    

      jobsatisfaction maritalstatus monthlyincome  monthlyrate  \
962                 4           NaN           NaN        10778   
578                 4           NaN        6502,0        22825   
843                 4       Married           NaN        16523   
1043                4       Married        5769,0         7100   
1418                2      Divorced        4187,0         3356   

      numcompaniesworked overtime  percentsalaryhike performancerating  \
962                    0      NaN                 17               3,0   
578                    4       No                 14               3,0   
843                    8      NaN                 15               3,0   
1043                   1      Yes                 11               3,0   
1418                   1      Yes                 13               NaN   

      relationshipsatisfaction  stockoptionlevel totalworkingyears  \
962                          4                 0               NaN   
578                          2                 1               NaN   
843                          3                 1               NaN   
1043                         4                 0               NaN   
1418                         2                 1              10,0   

      trainingtimeslastyear worklifebalance  yearsatcompany  \
962                       2             2,0               5   
578                       5             4,0               5   
843                       2             4,0               7   
1043                      3             3,0               6   
1418                      3             2,0              10   

      yearssincelastpromotion  yearswithcurrmanager  datebirth remotework  
962                         3                     4       1999      False  
578                         0                     1       1986          1  
843                         3                     7       1983       True  
1043                        4                     4       1996          1  
1418                        0                     9       1994       True

--------

- `Cambiar a float` ✅
- `Cambiar las comas(,) por puntos(.)` ✅

In [91]:
df['dailyrate'] = df['dailyrate'].str.replace(",", ".").str.replace("$", "")
df['dailyrate'].unique()

array(['684.0', '699.0', '532.0', '359.0', '1319.0', '117.0', '1435.0',
       '635.0', '1276.0', '840.0', '247.0', '1369.0', '201.0', '1360.0',
       '692.0', '1398.0', '286.0', '1402.0', '819.0', '884.0', '1238.0',
       '515.0', '1223.0', '202.0', '928.0', '607.0', '266.0', '429.0',
       '589.0', 'nan', '1180.0', '1282.0', '776.0', '665.0', '526.0',
       '1034.0', '1403.0', '1499.0', '580.0', '859.0', '263.0', '1376.0',
       '885.0', '1003.0', '1321.0', '394.0', '1372.0', '1333.0', '228.0',
       '737.0', '823.0', '667.0', '301.0', '573.0', '1329.0', '630.0',
       '1063.0', '1017.0', '1296.0', '939.0', '1355.0', '1448.0', '200.0',
       '1202.0', '404.0', '208.0', '813.0', '465.0', '1189.0', '1001.0',
       '1394.0', '161.0', '288.0', '682.0', '1354.0', '147.0', '119.0',
       '1413.0', '452.0', '334.0', '1132.0', '982.0', '480.0', '1099.0',
       '672.0', '1379.0', '583.0', '1492.0', '1050.0', '469.0', '237.0',
       '1440.0', '1291.0', '1157.0', '1336.0', '1224.0',

In [92]:
df['dailyrate'] = df['dailyrate'].astype(float)

In [93]:
df['dailyrate'].unique()

array([ 684.,  699.,  532.,  359., 1319.,  117., 1435.,  635., 1276.,
        840.,  247., 1369.,  201., 1360.,  692., 1398.,  286., 1402.,
        819.,  884., 1238.,  515., 1223.,  202.,  928.,  607.,  266.,
        429.,  589.,   nan, 1180., 1282.,  776.,  665.,  526., 1034.,
       1403., 1499.,  580.,  859.,  263., 1376.,  885., 1003., 1321.,
        394., 1372., 1333.,  228.,  737.,  823.,  667.,  301.,  573.,
       1329.,  630., 1063., 1017., 1296.,  939., 1355., 1448.,  200.,
       1202.,  404.,  208.,  813.,  465., 1189., 1001., 1394.,  161.,
        288.,  682., 1354.,  147.,  119., 1413.,  452.,  334., 1132.,
        982.,  480., 1099.,  672., 1379.,  583., 1492., 1050.,  469.,
        237., 1440., 1291., 1157., 1336., 1224.,  735., 1389.,  638.,
       1240.,  194., 1339.,  111., 1469.,  470., 1232., 1249.,  798.,
        549.,  570.,  541.,  164., 1117.,  619.,  319.,  956., 1245.,
       1397.,  527.,  213.,  882.,  330.,  406.,  217.,  481.,  669.,
       1465.,  685.,

In [94]:
df.sample()

age attrition businesstravel  dailyrate  distancefromhome  education  \
17   46        No  travel rarely     1402.0                 2          3   

   educationfield employeenumber  environmentsatisfaction  gender hourlyrate  \
17            NaN            NaN                        3       1         69   

    jobinvolvement  joblevel    jobrole  jobsatisfaction maritalstatus  \
17               3         4   MAnaGER                 1           NaN   

   monthlyincome  monthlyrate  numcompaniesworked overtime  percentsalaryhike  \
17           NaN        24097                   8      NaN                 23   

   performancerating  relationshipsatisfaction  stockoptionlevel  \
17               4,0                         1                 0   

   totalworkingyears  trainingtimeslastyear worklifebalance  yearsatcompany  \
17              28,0                      2             3,0              26   

    yearssincelastpromotion  yearswithcurrmanager  datebirth remotework  
17                       15                     9       1977      False

--------

Eliminado ❌

In [95]:
df['department'].unique()

KeyError: 'department'

In [ ]:
df['department'].isnull().sum() # Tiene un 81% de nulos

-----------

`Cambiar los números a positivos los que están negativos`✅

In [96]:
df['distancefromhome'] = df['distancefromhome'].abs()

In [97]:
df['distancefromhome'].unique()


array([ 6,  1,  4,  2,  3, 22, 25,  9,  7, 23, 10, 12, 14, 13, 15,  8, 42,
       28, 37,  5, 16, 35, 26, 24, 29, 17, 21, 18, 30, 27, 20, 31, 39, 11,
       19, 33, 34, 46, 36, 45, 47, 32, 41, 49, 48, 38, 43, 40, 44])

---------

No requiere cambios ✅

In [98]:
df['education'].unique()

array([3, 4, 2, 1, 5])

--------

- `cambiar a minúscula todo` ✅
- `Eliminar los NAN`

In [99]:
df['educationfield'] = df['educationfield'].str.lower()
df.head()

age attrition businesstravel  dailyrate  distancefromhome  education  \
0   51        No            NaN      684.0                 6          3   
1   52        No            NaN      699.0                 1          4   
2   42        No  travel rarely      532.0                 4          2   
3   47        No  travel rarely      359.0                 2          4   
4   46        No            NaN     1319.0                 3          3   

     educationfield employeenumber  environmentsatisfaction  gender  \
0               NaN          162,0                        1       0   
1     life sciences          259,0                        3       0   
2  technical degree          319,0                        3       0   
3           medical            NaN                        1       1   
4  technical degree            NaN                        1       1   

  hourlyrate  jobinvolvement  joblevel              jobrole  jobsatisfaction  \
0         51               3         5   resEArch DIREcToR                 3   
1         65               2         5             ManAGeR                 3   
2         58               3         5             ManaGER                 4   
3         82               3         4   ReseArCH DIrECtOr                 3   
4         45               4         4     sAleS EXECUtIve                 1   

  maritalstatus monthlyincome  monthlyrate  numcompaniesworked overtime  \
0           NaN       19537,0         6462                   7       No   
1           NaN       19999,0         5678                   0      NaN   
2       Married       19232,0         4933                   1       No   
3       Married       17169,0        26703                   3      NaN   
4      Divorced           NaN         7739                   2       No   

   percentsalaryhike performancerating  relationshipsatisfaction  \
0                 13               3,0                         3   
1                 14               3,0                         1   
2                 11               3,0                         4   
3                 19               3,0                         2   
4                 12               3,0                         4   

   stockoptionlevel totalworkingyears  trainingtimeslastyear worklifebalance  \
0                 0               NaN                      5             3,0   
1                 1              34,0                      5             3,0   
2                 0              22,0                      3             NaN   
3                 2               NaN                      2             NaN   
4                 1               NaN                      5             3,0   

   yearsatcompany  yearssincelastpromotion  yearswithcurrmanager  datebirth  \
0              20                       15                    15       1972   
1              33                       11                     9       1971   
2              22                       11                    15       1981   
3              20                        5                     6       1976   
4              19                        2                     8       1977   

  remotework  
0        Yes  
1          1  
2          1  
3      False  
4          0

In [100]:
df['educationfield'].unique()

array([nan, 'life sciences', 'technical degree', 'medical', 'other',
       'marketing', 'human resources'], dtype=object)

--------

Eliminado ❌

In [ ]:
df['employeecount'].unique()

-------

# `Eliminar duplicados`
- `Revisar bien cada registro para tomar una decisión sobre los nulos que tiene filas llenas pero el id es nulo`

In [101]:
df['employeenumber'].unique()

array(['162,0', '259,0', '319,0', ..., '2012,0', '2023,0', '2040,0'],
      dtype=object)

In [102]:
df['employeenumber'].duplicated().sum()

534

In [103]:
df['employeenumber'].value_counts()

employeenumber
482,0     2
530,0     2
507,0     2
517,0     2
522,0     2
         ..
161,0     1
164,0     1
190,0     1
194,0     1
2040,0    1
Name: count, Length: 1079, dtype: int64

In [104]:
df.duplicated(subset=['employeenumber'])

0       False
1       False
2       False
3       False
4        True
        ...  
1609     True
1610     True
1611     True
1612     True
1613     True
Length: 1614, dtype: bool

In [105]:
df_duplicated = df.loc[df.employeenumber == df.employeenumber, :]
df_duplicated.sample(10)

age attrition     businesstravel  dailyrate  distancefromhome  \
1053   41        No                NaN        NaN                 5   
868    49        No                NaN      636.0                10   
1350   29       Yes      travel rarely      906.0                10   
747    49       Yes  travel frequently     1475.0                28   
645    37        No      travel rarely     1470.0                10   
1019   28        No                NaN      791.0                 1   
1366   34        No                NaN      697.0                 3   
136    35        No                NaN      882.0                21   
1191   40        No                NaN     1469.0                 9   
577    31       Yes                NaN      307.0                29   

      education educationfield employeenumber  environmentsatisfaction  \
1053          5        medical         1448,0                        2   
868           4  life sciences          396,0                        3   
1350          3            NaN          994,0                        4   
747           2            NaN         1420,0                        1   
645           3            NaN         1640,0                        2   
1019          4        medical         1286,0                        4   
1366          4            NaN         1115,0                        3   
136           4            NaN          984,0                       21   
1191          4            NaN          964,0                        4   
577           2            NaN          355,0                        3   

      gender     hourlyrate  jobinvolvement  joblevel  \
1053       0             90               4         1   
868        1  Not Available               3         5   
1350       1             92               2         1   
747        0             97               2         2   
645        1             71               3         1   
1019       0             44               3         1   
1366       0             40               2         1   
136        0  Not Available               3         3   
1191       0  Not Available               3         1   
577        0             71               2         1   

                      jobrole  jobsatisfaction maritalstatus monthlyincome  \
1053      rEseaRCh SCIeNtIST                 3           NaN           NaN   
868        ReSEaRCh DIrECTOr                 1        Single       18665,0   
1350      rESEarCh scIenTisT                 1        Single           NaN   
747    laBoratOry TechNIcIaN                 1           NaN           NaN   
645       REsearch scIENtist                 2       Married        3936,0   
1019   LaBoRaToRy tEChniciAN                 3        Single           NaN   
1366      ResEaRCh sCiEnTIsT                 4           NaN           NaN   
136          SaLeS exEcuTIVE                 4           NaN           NaN   
1191      ResEarch ScIenTIst                 2           NaN        3617,0   
577    laboraTORy teChnICiaN                 2           NaN           NaN   

      monthlyrate  numcompaniesworked overtime  percentsalaryhike  \
1053         5561                   2      NaN                 12   
868         25594                   9      Yes                 11   
1350        11479                   6      Yes                 20   
747         22710                   3       No                 20   
645          9953                   1      NaN                 11   
1019         6842                   0      Yes                 11   
1366        22478                   3       No                 17   
136          6812                   6      NaN                 13   
1191        25063                   8      Yes                 14   
577         11652                   0       No                 11   

     performancerating  relationshipsatisfaction  stockoptionlevel  \
1053               3,0                         1                 0   
868                3,0

#### Muestra los duplicados juntos, se puede comparar cada fila

In [106]:
# Identificar los números de 'employeenumber' que están duplicados
employeenumber_counts = df['employeenumber'].value_counts()
duplicated_employeenumbers = employeenumber_counts[employeenumber_counts > 1].index

# Filtrar el DataFrame original para mostrar solo las filas con 'employeenumber' duplicados
df_duplicated_employeenumbers = df[df['employeenumber'].isin(duplicated_employeenumbers)]

# Ordenar por 'employeenumber' para verlos agrupados
df_duplicated_employeenumbers_sorted = df_duplicated_employeenumbers.sort_values(by='employeenumber')

# Mostrar el DataFrame resultante
df_duplicated_employeenumbers_sorted


age attrition businesstravel  dailyrate  distancefromhome  education  \
987    33        No     non travel     1038.0                 8          1   
1483   33        No     non travel     1038.0                 8          1   
1484   26       Yes            NaN      342.0                 2          3   
988    26       Yes            NaN      342.0                 2          3   
990    46        No            NaN      430.0                47          4   
...   ...       ...            ...        ...               ...        ...   
1609   36       Yes  travel rarely      530.0                 3          1   
367    45        No     non travel      805.0                47          2   
1610   45        No     non travel      805.0                 4          2   
369    36        No     non travel     1229.0                 8          4   
1612   36        No     non travel     1229.0                 8          4   

        educationfield employeenumber  environmentsatisfaction  gender  \
987      life sciences         1044,0                        2       1   
1483     life sciences         1044,0                        2       1   
1484     life sciences         1053,0                        1       0   
988      life sciences         1053,0                        1       0   
990            medical         1069,0                       47       0   
...                ...            ...                      ...     ...   
1609     life sciences          967,0                        3       0   
367                NaN          972,0                       47       0   
1610               NaN          972,0                        3       0   
369   technical degree          990,0                        1       0   
1612  technical degree          990,0                        1       0   

         hourlyrate  jobinvolvement  joblevel                  jobrole  \
987   Not Available               2         1    sALES ReprEsentatiVE    
1483             88               2         1    sales repResENTaTiVE    
1484             57               3         1      reSEArcH SCiEnTIst    
988              57               3         1      rEsEaRCH SCIenTiSt    
990              40               3         5       RESeArCH dIrEcTOR    
...             ...             ...       ...                      ...   
1609             51               2         3         saLEs ExeCUTiVe    
367              57               3         2   lABORaTory tecHNiCiAN    
1610             57               3         2   LAboRaTOry tECHNiCIAn    
369              84               3         2         SaLes EXeCuTiVE    
1612             84               3         2         SaLes ExecUtIVe    

      jobsatisfaction maritalstatus monthlyincome  monthlyrate  \
987                 4           NaN           NaN        21437   
1483                4           NaN           NaN        21437   
1484                1       Married        2042,0        15346   
988                 1       Married        2042,0        15346   
990                 4           NaN           NaN        21445   
...               ...           ...           ...          ...   
1609                4       Married       10325,0         5518   
367                 2           NaN        4447,0        23163   
1610                2           NaN        4447,0        23163   
369                 4      Divorced           NaN        25952   
1612                4      Divorced           NaN        25952   

      numcompaniesworked overtime  percentsalaryhike performancerating  \
987                    0      NaN                 19               3,0   
1483                   0      NaN                 19               3,0   
1484                   6      NaN                 14               3,0   
988                    6      NaN                 14               3,0   
990                    9       No                 17               3,0   
...                  ...      ...                ...  

### compara cada duplicado con sus columnas y ver similitud de info

In [107]:
# Función para comparar filas duplicadas
def compare_duplicates(df, key_column):
    # Identificar los números de 'key_column' que están duplicados
    key_counts = df[key_column].value_counts()
    duplicated_keys = key_counts[key_counts > 1].index

    # Filtrar el DataFrame original para mostrar solo las filas con 'key_column' duplicados
    df_duplicated_keys = df[df[key_column].isin(duplicated_keys)]

    # Ordenar por 'key_column' para verlos agrupados
    df_duplicated_keys_sorted = df_duplicated_keys.sort_values(by=key_column)

    # Comparar filas duplicadas
    comparison_results = {}
    for key in duplicated_keys:
        duplicated_rows = df_duplicated_keys_sorted[df_duplicated_keys_sorted[key_column] == key]
        comparison = duplicated_rows.apply(lambda x: x.nunique() == 1)
        comparison_results[key] = comparison[comparison == False].index.tolist()

    return comparison_results

# Comparar filas duplicadas para la columna 'employeenumber'
comparison_results = compare_duplicates(df, 'employeenumber')

# Mostrar los resultados de la comparación
for key, differences in comparison_results.items():
    if differences:
        print(f"EmpleyeeNumber {key} tiene diferencias en las columnas: {differences}")
    else:
        print(f"EmpleyeeNumber {key} no tiene diferencias en las columnas")


EmpleyeeNumber 482,0 tiene diferencias en las columnas: ['jobrole', 'maritalstatus', 'totalworkingyears', 'remotework']
EmpleyeeNumber 530,0 tiene diferencias en las columnas: ['educationfield', 'jobrole', 'worklifebalance', 'remotework']
EmpleyeeNumber 507,0 tiene diferencias en las columnas: ['businesstravel', 'distancefromhome', 'jobrole', 'maritalstatus', 'monthlyincome', 'totalworkingyears', 'remotework']
EmpleyeeNumber 517,0 tiene diferencias en las columnas: ['businesstravel', 'educationfield', 'hourlyrate', 'jobrole', 'maritalstatus', 'monthlyincome', 'remotework']
EmpleyeeNumber 522,0 tiene diferencias en las columnas: ['businesstravel', 'jobrole', 'overtime', 'remotework']
EmpleyeeNumber 523,0 tiene diferencias en las columnas: ['businesstravel', 'educationfield', 'jobrole', 'totalworkingyears']
EmpleyeeNumber 525,0 tiene diferencias en las columnas: ['businesstravel', 'educationfield', 'jobrole', 'maritalstatus', 'overtime', 'totalworkingyears', 'remotework']
EmpleyeeNumber 

# Eliminar duplicados de `employeenumber`, limpiar columna y ver que hacer con los nulos

In [108]:
# Eliminar duplicados en la columna 'employeenumber' y conservar solo la primera ocurrencia
df.drop_duplicates(subset='employeenumber', keep='first', inplace = True)

In [109]:
# Limpiar la columna 'employeenumber'
df['employeenumber'] = df['employeenumber'].astype(str).str.replace(',', '').str.strip()  # Reemplazar comas y eliminar espacios en blanco

In [110]:
# Convertir la columna 'employeenumber' a tipo numérico (int), manejando los posibles errores
df['employeenumber'] = pd.to_numeric(df['employeenumber'], errors='coerce')

In [111]:
df.shape

(1080, 32)

---------------------

No requiere cambios ✅

In [113]:
df['environmentsatisfaction'].unique()

array([ 1,  3,  4,  2, 37, 25, 27, 31, 39, 21, 15, 14, 33, 19, 12, 28, 47,
       36, 24, 13, 42, 16, 22, 41, 49, 11, 48, 18, 10, 38, 17, 20, 46, 45,
       35, 29, 26])

-------------

- `cambiar de 0 - 1 a Male/Female o M/F`✅
- `convertir en object ya que antes era int`✅


In [114]:
df['gender'] = df['gender'].replace({0: 'Male', 1: 'Female'})

In [115]:
df['gender'].unique()

array(['Male', 'Female'], dtype=object)

--------

- `Cambiar a formato de hora  o int`✅
- `Eliminar el Not Available`✅

In [116]:
# Rellenar los valores NA con 0 o cualquier otro valor predeterminado
df.hourlyrate = df.hourlyrate.replace({'Not Available': 0})


In [117]:

# Convertir la columna a enteros
df['hourlyrate'] = df['hourlyrate'].astype(int)

In [118]:
df['hourlyrate'].unique()

array([ 51,  65,  58,  82,  99,  64,  55,  49,  79,  31,  74,  98,  33,
        53,  87,  81,  84,  32,  92,  80,  47,  48,   0,  43,  86,  30,
        42,  57,  96,  67,  62,  72,  78,  89,  41,  90,  37,  45,  76,
        88,  60,  94, 100,  66,  54,  75,  61,  83,  85,  63,  44,  97,
        40,  46,  36,  35,  73,  56,  91,  52,  69,  70,  68,  38,  39,
        71,  77,  93,  95,  34,  59,  50])

------

No requiere cambios ✅

In [119]:
df['jobinvolvement'].unique()

array([3, 2, 1, 4])

-------

No requiere cambios ✅

In [120]:
df['joblevel'].unique()

array([5, 4, 3, 2, 1])

-----------

- `cambiar a minúsculas` ✅

In [121]:
df['jobrole'] = df['jobrole'].str.lower()

In [122]:
df['jobrole'].unique()

array([' research director ', ' manager ', ' sales executive ',
       ' healthcare representative ', ' manufacturing director ',
       ' laboratory technician ', ' research scientist ',
       ' sales representative ', ' human resources '], dtype=object)

-------

No requiere cambios ✅

In [123]:
df['jobsatisfaction'].unique()

array([3, 4, 1, 2])

-------

- `cambiar a minúsculas` ✅
- `Eliminar los NAN`
- `Eliminar la plabras 'Marreid' ` ✅

In [124]:
df["maritalstatus"] = df["maritalstatus"].str.lower()
df["maritalstatus"] = df["maritalstatus"].str.replace('marreid', 'married')

In [125]:
df['maritalstatus'].unique()

array([nan, 'married', 'single', 'divorced'], dtype=object)

-------

- ` quitar las comas por puntos `✅
- `tiene NAN`

In [126]:
def cambiar_comas(cadena):
    try:
        return float(cadena.replace(',', '').replace('.', ''))
    except:
        return np.nan
df['monthlyincome'] = df['monthlyincome'].apply(cambiar_comas)

In [127]:
df['monthlyincome'].unique()

array([195370., 199990., 192320., 171690., 171740.,     nan, 199730.,
       195450., 180410., 192460., 107480., 167520.,  40010., 104470.,
       160640.,  32100., 104750.,  61620.,  46150., 169590., 108550.,
        59140.,  66460., 139730., 133200.,  47350., 138720., 190450.,
        43060., 170460.,  23080.,  57470., 104220.,  63470.,  23480.,
        30720.,  80200., 170680., 192720.,  55770.,  26910.,  74030.,
        88230., 182130., 135770., 191900., 171230., 191870., 100080.,
        79880.,  70830.,  47230.,  34070.,  29290., 120310.,  51260.,
        96190.,  50100., 190330., 104000., 191970.,  84120.,  33480.,
        53090.,  76540., 128080.,  65860., 170990., 131200.,  31310.,
        66740.,  98520., 178610.,  74460., 165980.,  42850., 101240.,
        97140.,  99240., 112450.,  64720.,  83210.,  85780.,  41970.,
        98880., 133410.,  56770.,  29090.,  68250.,  44240.,  54410.,
        60740.,  61460.,  61720.,  46680.,  56050.,  35640.,  68040.,
        58280.,  245

-------

No requiere cambios ✅

In [128]:
df['monthlyrate'].unique()

array([ 6462,  5678,  4933, ...,  4060, 26956, 16642])

-------------------------

No requiere cambios ✅

In [129]:
df["numcompaniesworked"].unique()

array([7, 0, 1, 3, 2, 9, 4, 5, 6, 8])

-------

Eliminado ❌

In [ ]:
df['Over18'].unique()

-------

`hay un 42% de nulos, quizás eliminarla? - Eliminar los NAN`

In [130]:
df['overtime'].isnull().sum()/df.shape[0]

0.41388888888888886

In [131]:
df["overtime"].unique()

array(['No', nan, 'Yes'], dtype=object)

-------

No requiere cambios ✅

In [132]:
df['percentsalaryhike'].unique()

array([13, 14, 11, 19, 25, 17, 22, 12, 23, 21, 16, 15, 20, 18, 24])

-------

- `volverlo int o float` ✅
- `Quitarle la coma y por puntos` ✅
- `Eliminar los NAN `

In [133]:
df['performancerating'] = df['performancerating'].str.replace(",", ".")

In [134]:
df['performancerating'] = df['performancerating'].astype(float)

In [135]:
df["performancerating"].unique()

array([ 3.,  4., nan])

-------

No requiere cambios ✅

In [136]:
df["relationshipsatisfaction"].unique()

array([3, 1, 4, 2])

-------

Eliminado ❌

In [ ]:
df["standardhours"].unique()

-------

No requiere cambios ✅

In [137]:
df["stockoptionlevel"].unique()

array([0, 1, 2, 3])

-------

In [153]:
# Funición unica que cambia los valores de las columnas de totalworkingyears, worklifebalance

def cambiar_comas_y_nulos(cadena):
    if pd.isnull(cadena):  # Si es un valor nulo, devuelve NaN
        return np.nan
    try:
        return float(cadena.replace(',', '.'))  # Intenta convertir la cadena a float
    except ValueError:  # Si la conversión falla, devuelve NaN
        return np.nan

# Lista de las columnas que deseas modificar
columnas_a_convertir = ['totalworkingyears', 'worklifebalance']

# Aplica la función a cada columna en la lista
for columna in columnas_a_convertir:
    df[columna] = df[columna].apply(cambiar_comas_y_nulos)

- `Cambiar a int o float ` ✅
- `Eliminar los NAN `

In [140]:
df["totalworkingyears"].unique()

array([nan, 34., 22., 28., 20., 21., 40., 25., 15., 18., 26., 16., 24.,
       14., 23., 17., 27., 19., 11., 38., 37., 13., 12., 10., 33., 29.,
        9., 31., 35., 32., 36.,  8.,  7., 30.,  6.,  5.,  4.,  3.,  2.,
        1.,  0.])

-------

No requiere cambios ✅

In [141]:
df["trainingtimeslastyear"].unique()

array([5, 3, 2, 0, 1, 4, 6])

-----------

- `Tiene NAN`
- `cambiar a int o float` ✅


In [142]:
df['worklifebalance'].unique()

array(['3,0', nan, '2,0', '4,0', '1,0'], dtype=object)

-------

No requiere cambios ✅

In [143]:
df['yearsatcompany'].unique()

array([20, 33, 22, 21, 18, 31, 23, 15, 26, 16, 17, 14, 24, 13, 25, 12, 11,
       37, 36, 27, 10, 19,  9, 29, 30,  8,  7, 32,  6,  5,  4,  2,  3,  1,
        0])

-------

Eliminado ❌

- `tiene 97% null`

In [ ]:
df['yearsincurrentrole'].unique()

-------

No requiere cambios ✅

In [144]:
df['yearssincelastpromotion'].unique()

array([15, 11,  5,  4,  7,  0,  1, 13, 14,  8,  3, 12,  2, 10,  6,  9])

-------

No requiere cambios ✅

In [145]:
df['yearswithcurrmanager'].unique() 

array([15,  9,  6,  7, 11, 10,  8, 12,  4,  0,  5,  2, 14,  1, 17, 13,  3])

-------

Eliminado ❌

In [ ]:
df["sameasmonthlyincome"].unique()

-------

`Es str, creo que no requiere cambios es una fecha de año por si sola`✅

In [ ]:
df["datebirth"].unique()

-------

Eliminado ❌

In [ ]:
df["salary"].unique()

-------

Eliminado ❌

In [ ]:
df['roledepartament'].unique()

------

Eliminado ❌

In [ ]:
df["numberchildren"].unique()

-------


`Modificamos los valores 0 y 1, True or False por Yes y No` ✅
- 1  =      360
- True  =   345
- 0   =     309
- False =   305
- Yes  =    295

In [146]:
df['remotework']= df['remotework'].replace({('1'):'Yes',('0') or ('False'): 'No', 'True': 'Yes', 'False': 'No'})

In [147]:
df["remotework"].unique()

array(['Yes', 'No'], dtype=object)

In [148]:
df['remotework'].value_counts()

remotework
Yes    666
No     414
Name: count, dtype: int64

-------

#### `Mover el employeenumber al inicio` ✅

In [149]:
## Mover la columna 'employeenumber' al principio
df = df[['employeenumber'] + [col for col in df.columns if col != 'employeenumber']]

In [154]:
# Guarda el DataFrame como un archivo CSV
df.to_csv("df_superlimpiooo.csv", index = False)

# Punto final --> Limpieza de Nulos

### `Variables categóricas con Nulos = Objeto`

In [ ]:
# Obtenemos la lista de columnas categóricas que tienen nulos
nulos_esta_cat = df[df.columns[df.isnull().any()]].select_dtypes(include = "O").columns
print("Las columnas categóricas que tienen nulos son : \n ")
print(nulos_esta_cat)

In [ ]:
# sacamos el 'value_counts()' de cada una de las columnas categóricas que tienen nulos para saber como es la distribución de sus categorías
for col in nulos_esta_cat:
    print(f"La distribución de las categorías para la columna {col.upper()}")
    display(df[col].value_counts() / df.shape[0])  # display es una función utilizada para mostrar objetos de manera más legible en Jupyter Notebooks o entornos similares. 
    print("........................")

### `Variables numéricas con Nulos = Int o float`


In [ ]:
# Obtenemos la lista de columnas numericas que tienen nulos
nulos_esta_num = df[df.columns[df.isnull().any()]].select_dtypes(include = np.number).columns
print("Las columnas numéricas que tienen nulos son : \n ")
print(nulos_esta_num)

In [ ]:
# lo primero que vamos a hacer es calcular el número de nulos que tenemos en cada una de las columnas numericas
df[nulos_esta_num].isnull().sum() / df.shape[0]

In [ ]:
# Guarda el DataFrame como un archivo CSV
df.to_csv("DF_Totalmente_Limpio.csv", index = False)